### PR TITLE
Manpages: Ethernet interfaces

### PR DESCRIPTION
**Pull request by Mellvik**
This is the manage for the wd ethernet interfaces.

The 3c509 man page is forthcoming. A merge can wait until completed. 
There has to be typos and omissions in these man pages, we'll take them in stride.

-M

### CODE REVIEW

**Comment by Mellvik** [comment]
The latest commit also includes an update to the `man` command to enable man page file/command names to start with a number.

**Comment by ghaerr** [comment]
Looks good, let me know when you're ready for commit.

**Comment by Mellvik** [comment]
Thank you @ghaerr.We're good to go.While we're on man pages, I keep wondering if it's time to get rid of all those pages inherited from full Linux and not relevant to ELKS. As is I suspect they're more confusing than helpful. What's your take?-M12. des. 2022 kl. 16:36 skrev Gregory Haerr ***@***.***>:﻿
Looks good, let me know when you're ready for commit.

**Comment by ghaerr** [comment]
>  if it's time to get rid of all those pages inherited from full Linux and not relevant to ELKS.

The pages are actually from MINIX 3. You're welcome to delete any you think we'll never use - I already took a first pass, but left those that we might use in the future and possibly use some text from. If you like, we can discuss which ones you think we should delete before you submit the PR.

Thank you!

**Comment by Mellvik** [comment]
Admittedly it's a significant undertaking and there are some consideration to make.

For example, the termcap (5) man page is OK content wise but uses a number of commands and register manipulations not supported by ELKS man, and unlikely to be supported in the future. Such pages may be
- dropped, deleted (simple, the content exists elsewhere)
- simplified so that it may be displayed on ELKS (a significant undertaking)
- the ELKS man command may be expanded in such a way that unrecognised commands make it fork off a port of (minix) nroff with a reasonable macro library available which will be slow but doable.

What seems most reasonable to me is the first, just delete, add later if important and then limit to what's important for/supported by ELKS.

As to the cleanup suggested earlier, I think it makes sense to move the Minix manpages to a separate directory structure not being part of an ELKS build, but still available as references for ELKS-specific man pages - like now.


—M

**Comment by ghaerr** [comment]
Hello @Mellvik,

Thanks for the ideas and suggestions for dealing with the set of incorrect, irrelevant, not-yet-implemented, and not-displayed-properly man pages.

I like your idea of moving any of the above-described problem man pages to a separate `elkscmd/man-minix` directory tree such that they aren't actually installed into an ELKS image. They could still be reviewed using the portable `eman` command on macOS or Linux, and then moved back into the production `elkscmd/man/*` directory when updated.

Thank you!

**Pull request merged**
