### PR TITLE
tools/Makefile: update toolchain to newest version

### LINKED ISSUE #1169: Toolchain build fails
**Description**
I am trying to build ELKS toolchain on my Gentoo. It looks like, due newer? GCC, it fails. IIUC, -Werror=maybe-uninitialized seems the main cause, being set by default now?

Note: Using my Ubuntu 20.04 LTS vm works fine, but it uses older GCC.

```
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../binutils-src/bfd  -DBINDIR='"/home/conikost/elks/cross/bin"' -I. -I../../binutils-src/bfd -I../../binutils-src/bfd/../include  -DHAVE_i386_elf32_vec -DHAVE_i386_elks_vec -DHAVE_i386_msdos_vec -DHAVE_i386_aout_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec -DHAVE_plugin_vec   -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Werror -I../../binutils-src/bfd/../zlib -g -O2 -MT plugin.lo -MD -MP -MF .deps/plugin.Tpo -c -o plugin.lo ../../binutils-src/bfd/plugin.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../binutils-src/bfd -DBINDIR=\"/home/conikost/elks/cross/bin\" -I. -I../../binutils-src/bfd -I../../binutils-src/bfd/../include -DHAVE_i386_elf32_vec -DHAVE_i386_elks_vec -DHAVE_i386_msdos_vec -DHAVE_i386_aout_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec -DHAVE_plugin_vec -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Werror -I../../binutils-src/bfd/../zlib -g -O2 -MT plugin.lo -MD -MP -MF .deps/plugin.Tpo -c ../../binutils-src/bfd/plugin.c -o plugin.o
In function 'load_plugin',
    inlined from 'bfd_plugin_object_p' at ../../binutils-src/bfd/plugin.c:424:53:
../../binutils-src/bfd/plugin.c:403:20: error: 'valid_plugin' may be used uninitialized [-Werror=maybe-uninitialized]
  403 |         has_plugin = valid_plugin;
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~
../../binutils-src/bfd/plugin.c: In function 'bfd_plugin_object_p':
../../binutils-src/bfd/plugin.c:397:11: note: 'valid_plugin' declared here
  397 |       int valid_plugin;
      |           ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [Makefile:1602: plugin.lo] Error 1
make[5]: Leaving directory '/home/conikost/elks/cross/build/binutils-build/bfd'
make[4]: *** [Makefile:1645: all-recursive] Error 1
make[4]: Leaving directory '/home/conikost/elks/cross/build/binutils-build/bfd'
make[3]: *** [Makefile:1170: all] Error 2
make[3]: Leaving directory '/home/conikost/elks/cross/build/binutils-build/bfd'
make[2]: *** [Makefile:2691: all-bfd] Error 2
make[2]: Leaving directory '/home/conikost/elks/cross/build/binutils-build'
make[1]: *** [Makefile:849: all] Error 2
make[1]: Leaving directory '/home/conikost/elks/cross/build/binutils-build'
make: *** [Makefile:54: /home/conikost/elks/cross/build/.binutils.build] Error 2
make: Leaving directory '/home/conikost/elks/tools'
Build script has terminated with error 1
```

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/11.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-11.2.1_p20220115/work/gcc-11-20220115/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/11.2.1 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/11.2.1 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/11.2.1/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/11.2.1/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/include/g++-v11 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/11.2.1/python --enable-languages=c,c++,jit,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --disable-libunwind-exceptions --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 11.2.1_p20220115 p4' --disable-esp --enable-libstdcxx-time --with-build-config=bootstrap-lto --disable-libstdcxx-pch --enable-host-shared --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --disable-cet --disable-systemtap --disable-valgrind-annotations --enable-vtable-verify --with-zstd --enable-lto --with-isl --disable-isl-version-check --enable-default-pie --enable-default-ssp
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.1 20220115 (Gentoo 11.2.1_p20220115 p4)
```

### PR DESCRIPTION
**Pull request by ConiKost**
@tkchia Any objections?

Closes: https://github.com/jbruchon/elks/issues/1169
Signed-off-by: Conrad Kostecki <conikost@gentoo.org>

### CODE REVIEW

**Comment by ghaerr** [comment]
Hello @ConiKost,

Thank you for discovering that the latest version of the ELKS toolchain works for you to compile and use ELKS on Gentoo.

Given that we have lots of current development and submissions going on, and that more testing needs to be done to ensure all works well between the contributing developers on various platforms, I'm going to hold on upgrading the toolchain at this time. Note that EMU86, for instance, cannot be upgraded past the version in use, as the hardware emulated timer change broke emulation of the ELKS kernel.

Thank you!

**Comment by ConiKost** [comment]
Hi @ghaerr 

Yep, that's fine for me. 

I may have a small favor: Could we somehow introduce a local config, which is in .gitignore, so I could in my local checkout overwrite the toolchain version? Currently, git will always detected the change. That would make it possible to override locally my toolchain version without need to commit it.

**Comment by ghaerr** [comment]
> Currently, git will always detected the change.

The ELKS repo does not contain any of the toolchain files used in the 'cross' directory (except version numbers in tools/Makefile, and if tools/build.sh is not run, then your (updated) toolchain will never be rebuilt automatically, even with a "git pull" to the most recent version. This is by design, so that developers are not required to update their toolchain, even when tools/Makefile is updated (although they might).

I'm not a git expert, and not familiar with local configs. Are you suggesting introducing them so you can keep track of your modified tools/Makefile? Perhaps just copying it to Makefile.gentoo could work. At some point, we will certainly upgrade the toolchain; in the past, we've done this when requiring a feature that is needed in ELKS.

**Comment by ConiKost** [comment]
> Are you suggesting introducing them so you can keep track of your modified tools/Makefile? Perhaps just copying it to Makefile.gentoo could work.

Basically yes. I have done a PR https://github.com/jbruchon/elks/pull/1177, which would solve it.
It makes possible to override all ```_VER``` variables in a new file called ```Make.local```, but we can take a different name, if you wish.

**Pull request closed without merging**
