### PR TITLE
[kernel] Rewrite WD network driver to skip recv_buf buffering

### PR DESCRIPTION
**Pull request by ghaerr**
Hello @pawosm-arm,

Here's wd.c rewritten, and completely untested, to perform the following:
- Use a far pointer to access the ethernet header rather than copying it.
- Remove 256 byte fmemcpy of guessed packet size.
- Remove second fmemcpy if packet size > 256
- Replace both with single fmemcpy directly into requesting application's buffer.
- Fixes build problem with net_drv.a having the same eth_drv_init() symbol.

If this works, I will push another commit to do remove the write buffer send_buf (unless you'd like to).

Thanks!

### CODE REVIEW

**Comment by pawosm-arm** [comment]
Looking at it. Seems it requires toolchain rebuild to it will take some time to complete.

**Comment by ghaerr** [comment]
> Seems it requires toolchain rebuild to it will take some time to complete.

No - sorry, the tools/Makefile change is an attempt to debug a problem with @tkchia's update earlier this morning. You shouldn't need to rebuild the toolchain unless you never did the rebuild several days ago.

**Comment by pawosm-arm** [comment]
I did the rebuild few days ago. So now I'm just rebuilding the kernel.

**Comment by ghaerr** [comment]
> I did the rebuild few days ago. So now I'm just rebuilding the kernel.

Great. I just confirmed with @tkchia that the problem is in fact with the tools/Makefile version number, so I will commit that fix along with these wd.c changes if this works, so that no compiler update is needed.

**Comment by pawosm-arm** [comment]
Bad news. The kernel does not start. All it prints is:

```
t00C0 f0DE0 d0F02 t
```

**Comment by ghaerr** [comment]
> I did the rebuild few days ago. So now I'm just rebuilding the kernel.

Ok, lets proceed slowly so we don't have a mess on our hands. Given that the compiler toolchain was just messed up by a commit this morning, follow these steps in order:

- Check that tools/Makefile shows the following line
```
BINUTILS_VER=f19a905d1434da03940951913514a9ef12f0d7dd
```
- Run "make clean; make menuconfig", then make.

If the kernel still fails, remove the Far Text Option in Kernel -> Kernel settings, make clean and make.

The console startup runs before anything networking related, so this isn't to do with wd.c.

If you still have problems, then I will have to commit a fix for @tkchia's version number separately, then reupload this PR after figuring out what exactly is going on on your system.

**Comment by pawosm-arm** [comment]
Would it be enough if I cherry-pick your commit on top of my wd8003 branch?

**Comment by ghaerr** [comment]
> Would it be enough if I cherry-pick your commit on top of my wd8003 branch?

Yes - here's a patch. Try to use as much as possible.

Thank you!
[wd.patch.zip](https://github.com/jbruchon/elks/files/5287210/wd.patch.zip)

**Comment by pawosm-arm** [comment]
Hey, cherry-pick worked (with a small conflict easy to fix), the driver works, some gain on ping observed:

```
$ ping -i 0.5 -s 1400 192.168.1.44
PING 192.168.1.44 (192.168.1.44) 1400(1428) bytes of data.
1408 bytes from 192.168.1.44: icmp_seq=1 ttl=64 time=49.5 ms
1408 bytes from 192.168.1.44: icmp_seq=2 ttl=64 time=49.5 ms
1408 bytes from 192.168.1.44: icmp_seq=4 ttl=64 time=49.8 ms
1408 bytes from 192.168.1.44: icmp_seq=5 ttl=64 time=49.5 ms
1408 bytes from 192.168.1.44: icmp_seq=6 ttl=64 time=49.6 ms
1408 bytes from 192.168.1.44: icmp_seq=7 ttl=64 time=49.5 ms
1408 bytes from 192.168.1.44: icmp_seq=9 ttl=64 time=49.5 ms
1408 bytes from 192.168.1.44: icmp_seq=10 ttl=64 time=49.5 ms
1408 bytes from 192.168.1.44: icmp_seq=11 ttl=64 time=49.5 ms
^C
--- 192.168.1.44 ping statistics ---
11 packets transmitted, 9 received, 18.1818% packet loss, time 5010ms
rtt min/avg/max/mdev = 49.483/49.551/49.754/0.078 ms
```

**Comment by ghaerr** [comment]
> Hey, cherry-pick worked (with a small conflict easy to fix), the driver works, some gain on ping observed:

Can you show me exactly what needs to be changed?

I either need to commit this PR or #766 immediately so we can resolve a compiler toolchain issue. Thanks!

**Comment by pawosm-arm** [comment]
Just one file, this is the solved diff:

```
diff --git a/elks/include/linuxmt/init.h b/elks/include/linuxmt/init.h
index f6a7790f..09264286 100644
--- a/elks/include/linuxmt/init.h
+++ b/elks/include/linuxmt/init.h
@@ -43,5 +43,6 @@ extern void mem_dev_init(void);
 extern void init_bioshd(void);
 
 void eth_drv_init (void);
+extern void wd_drv_init(void);
 
 #endif
```

**Comment by ghaerr** [comment]
Thanks @pawosm-arm. I have the above change already made in another spot, so everything is fine.

I am going to commit this now, which enhances your driver, and also reverts the toolchain issue.

I will then submit, in another PR, the changes to wd.c to remove the send_buf double buffering, along with a patch file for your ease of testing.

**Comment by pawosm-arm** [comment]
what about master branch? shall I rebuild the toolchain to make it usable?

**Comment by ghaerr** [comment]
> what about master branch? shall I rebuild the toolchain to make it usable?

Yes. You should now do a new git pull upstream master, then run make clean; then tools/build.sh. It will automatically rebuild the toolchain if you need it.

**Comment by pawosm-arm** [comment]
I still had to disable "Far Text Option" to make it boot...

**Comment by ghaerr** [comment]
> I still had to disable "Far Text Option" to make it boot...

Interesting. Well - you could be the very first one to actually test the far text kernel on real hardware! I'll add this boot problem to my TODO list and also test on real hardware. @tkchia has just found some other issues as well. Stay tuned, and thanks for your testing!

**Pull request merged**
