### PR TITLE
Third burst of patches from Marcin

### PR DESCRIPTION
**Pull request by mfld-fr**
Patches from the mailing list:
* HTML format nicing
* Split of `libc` modules to save user space

### CODE REVIEW

**Review by marcin-laszewski — APPROVED** [review]

**Comment by mfld-fr** [comment]
@marcin-laszewski : do you want me to merge these 2 commits now or should I also add your latest patches related to the LIBC modules splitting ?

**Comment by marcin-laszewski** [comment]
Add last LIBC patches, please.

**Comment by mfld-fr** [comment]
To be rebased on latest HEAD. Closing for now.

**Review by marcin-laszewski — COMMENTED** [review]
OK

**Pull request closed without merging**
