### PR TITLE
Update 8018x configuration

### PR DESCRIPTION
**Pull request by mfld-fr**
Update `8018X` configuration after testing on EMU86 with preliminary support of OR556.
Used `8018x.config` for ELKS configuration, and `config-or556.mk` for EMU86.

### CODE REVIEW

**Comment by mfld-fr** [comment]
I think @cocus will need this one when he will resume his port.

**Comment by ghaerr** [comment]
@mfld-fr : Looks fine, thank you.

@cocus : you will want to change the following lines for testing on 128K, as discussed in https://github.com/jbruchon/elks/issues/932#issuecomment-844546078:
```
CONFIG_FS_EXTERNAL_BUFFER=y
CONFIG_FS_NR_EXT_BUFFERS=1
```
I noticed a compile problem when setting CONFIG_FS_EXTERNAL_BUFFER=n; I will fix that separately.

I checked, and you will be able to run ELKS on your 128K RAM system with the above modifications to config (11K to spare! :)

If you haven't yet written the kernel timer callback code for the keyboard polling, I can supply that with a quick PR, which will share some slightly modified code in kbd-bios.c. All you will need to write is the 8018X serial receive polling routine. This is discussed in detail in https://github.com/jbruchon/elks/issues/932#issuecomment-843745315.

Let me know if you'd like me to post the shared console polling routine to ease your progress in this port, thanks!



`

**Comment by cocus** [comment]
@ghaerr Please go ahead if you have time to do so. I still need to sync all the changes you (and @mfld-fr) have added on elks and emu86 and test it tonight if I have some time!

**Comment by ghaerr** [comment]
@cocus Ok I will post a PR that will require just three serial routines for the 8018X: `coninit` (possibly empty), `conout` (already written), and `conpoll` in a single file. I'll move any code you've already written so you don't have to do it. All other code should be automatically shared.

It may take me until later tonight to get this done, thanks!

**Comment by ghaerr** [comment]
@cocus : PR #952 should allow you to move forward quickly with your port, by just writing a single routine for polling the serial port. See conio-8018x.c. Let me know if you have any questions, thanks!

**Pull request merged**
