### PR TITLE
[sash] bugfixes in history, added mount -a

### PR DESCRIPTION
**Pull request by Mellvik**
- history bug fixes 
- catch accidental arrow keypresses
- add new `mount -a` option

### CODE REVIEW

**Comment by ghaerr** [comment]
Thanks @Mellvik, and sorry for the trouble on the last PR!

**Comment by Mellvik** [comment]
You know - git is a big animal, some times unpredictable. My cleanup (!) seems to have had adverse effects on my pending changes to ftp/ftpd - so I'm in recovery mode.

BTW - building 1440 images no longer works - running out of space, (needs 1460 got 1440), can you help? Or did I miss a new setting in config?

```
for DIR in ; do /Library/Developer/CommandLineTools/usr/bin/make -C $DIR install || exit 1; done
mkdir /Users/helge/src/mellvik/elks/target/lib/man1; cp -rp man/man1 /Users/helge/src/mellvik/elks/target/lib
mkdir: /Users/helge/src/mellvik/elks/target/lib: No such file or directory
mkdir /Users/helge/src/mellvik/elks/target/lib/man5; cp -rp man/man5 /Users/helge/src/mellvik/elks/target/lib
mkdir /Users/helge/src/mellvik/elks/target/lib/man8; cp -rp man/man8 /Users/helge/src/mellvik/elks/target/lib
/Library/Developer/CommandLineTools/usr/bin/make -C /Users/helge/src/mellvik/elks/bootblocks
make[3]: Nothing to be done for `all'.
bash -c "./ver.pl /Users/helge/src/mellvik/elks/elks/Makefile-rules > /Users/helge/src/mellvik/elks/target/etc/issue"
git log --abbrev-commit | head -1 | sed 's/commit/ELKS built from commit/' > /Users/helge/src/mellvik/elks/target/etc/motd
install /Users/helge/src/mellvik/elks/elks/arch/i86/boot/Image /Users/helge/src/mellvik/elks/target/linux
rm -f /Users/helge/src/mellvik/elks/image/fd1440.img
mfs  /Users/helge/src/mellvik/elks/image/fd1440.img genfs -1 -n14 -i256 -s1440 /Users/helge/src/mellvik/elks/target
Blocks required 1460, available 1440

make[2]: *** [minixfs] Error 255
make[1]: *** [image] Error 2
make: *** [all] Error 2

```

**Comment by ghaerr** [comment]
> My cleanup (!) seems to have had adverse effects on my pending changes to ftp/ftpd - so I'm in recovery mode.

Yes, I would be very careful when changing head and forcing commits... hopefully that didn't delete your changes to ftp. I always do "git diff > foo.patch" before committing, for a variety of reasons.

> building 1440k images no longer works - running out of space, (needs 1460 got 1440), can you help

I'll fix that, seems we've all added too much stuff lol, and another less-used program needs to be removed from the 1440K distribution. I missed this because my default build is now 2880k so I can get the man pages...

Time for some compressed executables :)

**Comment by ghaerr** [comment]
> building 1440 images no longer works - running out of space, (needs 1460 got 1440), can you help? Or did I miss a new setting in config?

The reason is different than I thought - you have man pages turned on in config. These will no longer fit on 1440K, so that option needs to be turned off. 

I have the other fixes coming shortly.

**Comment by Mellvik** [comment]
Thanks, 
I did indeed miss the new man page config option,

Appreciated.

-M

**Pull request merged**
