### PR TITLE
[cmds] Bugfixes in sys and cp

### PR DESCRIPTION
**Pull request by Mellvik**
The `/bin` directory is now so big that `/bin/*`  will cause `sark` problems for several apps, including `cp`. So `sys` failed. Changed the script to use `cp -R .` instead, and fixed `usage()`.

Also changed default verbose mode to off in `cp`.

### CODE REVIEW

**Comment by ghaerr** [comment]
Will the script still run by using "cp -R /bin $MNT/bin"? That would be preferable to having to change the directory within the script (not changing the current directory may be desirable for other operations).

**Comment by Mellvik** [comment]
Yes, it does work that way too. I probably botched something when testing. Absolutely preferable.

BTW - sys -M works well on any partition, needs fdisk to set active partition. Maybe a message to that effect at the end of sys would be good. 

-M

**Comment by ghaerr** [comment]
> BTW - sys -M works well on any partition, needs fdisk to set active partition. 

Thanks for that testing. It is possible we could have `makeboot` (which is called by sys -M to write the partition boot block) activate the partition in the MBR, but that may not be what the user desires.

> Yes, it does work that way too. Absolutely preferable.

Great. Please change that and we'll commit. We can decide whether to change sys -M behavior in a subsequent commit.

Thank you!

**Comment by Mellvik** [comment]
> 
> BTW - sys -M works well on any partition, needs fdisk to set active partition.
> 
> Thanks for that testing. It is possible we could have makeboot (which is called by sys -M to write the partition boot block) activate the partition in the MBR, but that may not be what the user desires.
> 
Agreed, so it should either be optional or just a message at exit time to that effect.
> Yes, it does work that way too. Absolutely preferable.
> 
> Great. Please change that and we'll commit. We can decide whether to change sys -M behavior in a subsequent commit.
> 
Coming up.

> Thanks,
> 
> M

**Pull request merged**
