### PR TITLE
[net, ftp] bugfixes in ftp

### PR DESCRIPTION
**Pull request by Mellvik**
Fixes the following issues:

- incoming (`get`) zero length files would some times cause ftp to hang because server closed connection to early. See #1048 (discussion).
- when open connection failed, the terminal input remained open and `ftp` would run out of memory.
- Improved server timeout detection.

### CODE REVIEW

**Comment by ghaerr** [comment]
@Mellvik,

Thanks for identifying and fixing the zero-length file problem.

Is this ftp out-of-memory fix the only one, or is there still a ktcp memory problem?

Thank you!

**Comment by Mellvik** [comment]
Thank you @ghaerr,
> Thanks for identifying and fixing the zero-length file problem.
> 
Yes, the problem is fixed as far as ftp is concerned, and it may be too much of a special case to go after the real problem in ktcp.
> Is this ftp out-of-memory fix the only one, or is there still a ktcp memory problem?
> 
Ktcp is in the clear. It runs out of memory when it should, so to speak - too many sockets, but the crunch is handled properly. I've been running two ftp clients and one active server concurrently on elks and get lots of sbrk errors (and failed file transfers), but no crashes. Really good.

I found that - when all this is going on concurrently, netstat some times report the same connection twice. Again this is probably too esoteric to worry about.

I'm still experimenting with heap numbers on ftp and ftpd - expandwildcards some times seem to eat more that reasonable.

--M

**Comment by Mellvik** [comment]
An additional comment about `ktcp`, @ghaerr:

Under heavy load, `ktcp` will eventually hang.
An incoming ftp connection doing many back-to-back outbound (`mget *` from the client) transfers in PORT mode (ELKS connection back to the client for the data channel), will generate a lot of
```
  tcp: port 20 REUSED, freeing previous socket in time_wait                     
  tcp: port 20 NOT reused, previous socket in state 4     
```
and an occasional 
```
Bind: Could not connect on port 20                                              
bind error:   Address already in use 
```
The 'strained' conditions seem to be handled gracefully though, there are no transfer errors.
When an outbound `ftp` is running concurrently with the one above, movie back-to-back files into ELKS (`mget *`), there will be occasional retransmits:
```
tcp retrans: seq 10501 size 512 rcvwnd 65535 unack 988 rto 16 rtt 4 (RETRY 1 cnt 2 mem 1028)                                                        
tcp retrans: seq 10025 size 476 rcvwnd 65535 unack 988 rto 20 rtt 4 (RETRY 1 cnt 2 mem 1028)
```
 It seems to me that either the combination or the latter is what eventually causes `ktcp` to hang. At this point, `ktcp` may be killed and the connections will eventually time out.

**Comment by ghaerr** [comment]
> Under heavy load, ktcp will eventually hang.

Thanks for the detailed report, Helge. 

You are really putting ELKS through some heavy work, and overall it is performing quite well. I think we may be reaching the higher side of network reliability for ELKS, although I'm sure there's more bugs to be found. 

For instance, I have a working `alarm` (requested in #1090), that I also added code to work with networking to allow a `connect` to return in, say 10 seconds, if not connected. However, there are problems with the architecture of ktcp being outside the kernel: the client/server approach between them does not allow for unexpected events to be communicated easily. If the alarm fires, the kernel is interrupted and returns -ETIMEDOUT, but ktcp doesn't know about any of this, and there's no easy way to tell it. It's still got an open TCP CB, waiting for a SYN response to its SYN sent. That special handling code needs to be written to allow alarm to be used with arbitrary ELKS networking programs. I don't see any easy way to do it that will always work.

Of course, the ktcp lower level could be modified to somehow accept a "cancel" request, but this would also have to be done for "accept", and possibly all other network operations, and each have their own race conditions that might pop up later. For instance, if the alarm went off, but just before the cancel request, the ktcp accepted a connection, this could leave ktcp in a state where further connection requests wouldn't work, etc. The asynchronous nature of the kernel and ktcp is making things quite complicated at the level of reliability we're at.

I'm sure all of this, including reliability issues, could be solved of course, but I feel it may be getting exponentially harder to handle all the cases.

Given all your testing and simultaneous applications and transfers running, I'd say ELKS is doing quite well.

**Comment by Mellvik** [comment]
Thank you, @ghaerr - 
I agree - ELKS is doing really well on most fronts these days. And yes, I'm pushing reasonable limits when testing, and while doing so it's easy to forget that we're not creating the next VAX - for 100 serial and 50 network users. But rather a single user multi process system which can do wonders with limited resources. This is exactly what ELKS does.
Which brings up a network related issue we've touched before: Creating a container for packet drivers to make them work in ELKS. It may well be more efficient use of time than writing (say) new network drivers.

Back to the case at hand, I fully appreciate the complications you describe and understand their reason and consequences. Now, with alarm() or setitimer() available, how about delegating the issue to ktcp without involving the kernel? Could ktcp have its own little timeout loop kicking off every second, checking on (say) SYNs sent and not responded to? Assuming ktcp has the capability to tear down the incomplete connection in the same way it would if a FIN arrived.

Thanks again for a thorough rundown.

--Mellvik

**Comment by ghaerr** [comment]
Hello @Mellvik,

> how about delegating the issue to ktcp without involving the kernel? Could ktcp have its own little timeout loop kicking off every second, checking on (say) SYNs sent and not responded to?

Yes, that's probably a good way to solve the connect issue. Instead of using an application-based alarm, ktcp could just handle connect timeouts automatically, with a much lower timeout - say 10 seconds. This could be changed with a new SO_TIMEOUT option.

For accept timeouts, we could also use SO_TIMEOUT or something similar. The kernel would not be involved in any timeout, instead, ktcp would notify the kernel that the accept (or connect, as in above) had expired.

I'll add connect timeouts to my list. Do we really need an accept timeout capability?

Regarding alarm - I'll just keep the current implementation on hold. It could be useful in general, but if used for network timeouts, it will introduce unreliability into the networking system. Thoughts?

Thank you!

**Comment by Mellvik** [comment]
@ghaerr,

> 
> how about delegating the issue to ktcp without involving the kernel? Could ktcp have its own little timeout loop kicking off every second, checking on (say) SYNs sent and not responded to?
> 
> Yes, that's probably a good way to solve the connect issue. Instead of using an application-based alarm, ktcp could just handle connect timeouts automatically, with a much lower timeout - say 10 seconds. This could be changed with a new SO_TIMEOUT option.
> 
Yes this is good!
> For accept timeouts, we could also use SO_TIMEOUT or something similar. The kernel would not be involved in any timeout, instead, ktcp would notify the kernel that the accept (or connect, as in above) had expired.
> 
> I'll add connect timeouts to my list. Do we really need an accept timeout capability?
> 
IIRC accept (in most systems) can be declared nonblocking  - I don't know if it's implemented in ELKS. If it isn't I'd think it's better to put that on the list.
> Regarding alarm - I'll just keep the current implementation on hold. It could be useful in general, but if used for network timeouts, it will introduce unreliability into the networking system. Thoughts?
> 
You're seeing sides of this that I don't. My take is that it would be very useful for (say) daemons to be able to close down idle connections. Such as ftpd - closing down after 900 seconds, which seems to be the norm. But there is noe rush on this one.

Thank you - we're getting there.

-M

**Pull request merged**
