### PR TITLE
Docs5

### PR DESCRIPTION
**Pull request by georgp24**
Update of index.html in Documentation directory. Remove dead links, group links, add missing files, convert shell.txt into shell.html. 
Added Readme.md file which contains links to all the documents listed in index.html. This way the documents can be read from a browser while on the GitHub site. Link to this file from main README.md file.

### CODE REVIEW

**Comment by ghaerr** [comment]
Very nice @georgp24, you're really going to town on the documentation update, thanks!

The Readme.md is very useful.

The ELKS website I was talking about earlier, that might be used to "point" to the documentation (and also be updated) is http://elks.sourceforge.net. **Do you know who maintains that site?** It is quite out of date, and I'd like to work with you about getting it updated.

**Comment by georgp24** [comment]
Jody Bruchon has access to the SourceForge site. SourceForge offers to host a web page (or more?) for your project. I think the ELKS web page is placed this way on SourceForge.

**Comment by ghaerr** [comment]
Thanks, I'll take to Jody about it. It would be nice to have links to the updated documentation from there, as well as having the home page updated. I plan on updating the main Github Readme.md shortly, as the build instructions have changed slightly.

**Comment by ghaerr** [comment]
Hi @jbruchon,

Are you the maintainer of the ELKS website at http://elks.sourceforge.net, or do you know who is?
There has been some discussion of updating it, since it's still vintage 0.2.0 or so. 
It would be nice if the website source were on GitHub, but given that it's sourceforge, probably not possible?

**Comment by jbruchon** [comment]
I do have control over that, yes. The website has to be updated on SourceForge over SSH, unfortunately, unless they've changed something. Admittedly, I haven't actually made use of SourceForge for anything in years.

**Pull request merged**
