### PR TITLE
[kernel] Swap back code and data segment

### PR DESCRIPTION
**Pull request by mfld-fr**
Prepare the data segment extent to maximum (64K) and local heap introduction.

### CODE REVIEW

**Comment by ghaerr** [comment]
Hello @mfld-fr,

I don't quite yet understand what this is doing, can you explain it a bit more? I referenced this in a comment on #440 and don't know exactly which problem this is solving.

**Comment by mfld-fr** [comment]
@ghaerr : all is already explained in #440 

@tkchia : can you review please ?

**Comment by tkchia** [comment]
Hello @mfld-fr,

Thanks --- it looks OK (so far) to me.

Well, except for one thing: `do_bioshd_request()` does not seem to limit the size of each disk I/O request to the size of the DMA buffer (`DMASEG:0`)?

Perhaps there should be a `DMASEGSZ` constant or some such to give the size of this DMA buffer, and the `DMA_OVR` code should limit each disk I/O request to this number of bytes.

Thank you!

**Comment by mfld-fr** [comment]
@tkchia : Do you mean a more explicit limitation than the current one in lines 706 and 729 ?

**Comment by tkchia** [comment]
Hello @mfld-fr,

> @tkchia : Do you mean a more explicit limitation than the current one in lines 706 and 729 ?

Yes.  Thank you!

**Comment by ghaerr** [comment]
Hello @mfld-fr,

Do you want this committed now, or are you making a change per @tkchia's review on lines 706/729?

**Comment by mfld-fr** [comment]
@ghaerr : I think @tkchia is right when asking a more 'safe' limit to not overflow DMASEG.

**Comment by mfld-fr** [comment]
@tkchia : added the 'safer' limit.

**Comment by ghaerr** [comment]
Hello @mfld-fr,

I think I understand this PR now, but am trying to keep up with you and @tkchia on the DMA boundary issue and this PR: It seems that we don't do BIOS disk reads into L1 or L2 buffers yet, that instead, all doshd.c I/O uses DMA and goes into the DMASEG buffer, which this PR is now relocating and enhancing? Then, that DMA buffer contents are copied using `fmemcpy` to another buffer, is that correct?

If so, then the suggestion of moving the L1 buffers to a 1k boundary is moot, since no I/O occurs directly into them, right?

**Comment by mfld-fr** [comment]
@ghaerr : correct, temporary use of DMASEG (until I/O directly in L2 buffers) relaxes the alignment constraint on the L1 buffers, so they are now free to be allocated anywhere in the kernel data segment with the upcoming heap allocator.

**Pull request merged**
