### PR TITLE
[minix] Fix buffer problems and filesystem check status in MINIX filesystem

### PR DESCRIPTION
**Pull request by ghaerr**
This fixes the MINIX filesystem check status bug brought up in #404, and corrects and cleans up various other buffer issues in the MINIX filesystem.

### CODE REVIEW

**Comment by mfld-fr** [comment]
It would be easier to distinguish actual bug fixes and spacing changes if you could stop to mix them within the same commit...

**Comment by jbruchon** [comment]
I'm squashing mutli-commits anyway, so it does not matter.

**Comment by mfld-fr** [comment]
@jbruchon : True after the merge, false when reviewing before the merge.

**Comment by ghaerr** [comment]
Hello @mfld-fr,

> It would be easier to distinguish actual bug fixes and spacing changes if you could stop to mix them within the same commit...

I understand what you mean, and will try to do so in the future. It's just that with the mixed spaces and tabs approach used in a lot of the source, it's hard to understand the whole of the code without reformatting it to be completely understandable. Would you mind various other commits just for reformatted readability in the future?

With regards to the bug fix itself - the problem wasn't the unmap_buffer call at the end of read_super. Instead, a pointer to a mapped buffer was saved in the memory superblock, which was then used to access the filesystem checked flag when remounting or unmounting. I removed that pointer and instead remapped the buffer in both those cases, while also cleaning up the code considerably by putting most of that into a new routine, minix_set_super_state. Another flag was added to the memory super_block to save the super check state to save an additional map buffer in remount. The rest of the commit is cleanup and reformatting.

**Comment by mfld-fr** [comment]
OK, got it, thanks.

**Pull request merged**
