### PR TITLE
[basic] Add COLOR, DRAW, CIRCLE and int1C handler to basic for PC-98

### PR DESCRIPTION
**Pull request by tyama501**
Hello @ghaerr , @cocus ,

As I wrote on #1238 , I added color, draw, circle command to basic.

I added stubs in host-stubs.c and host-8018x.c but sorry if merging is needed.

I also modified README.md.
Please tell me farther modification is needed.

Thank you!

### CODE REVIEW

**Comment by ghaerr** [comment]
Thank you for this contribution @tyama501, and great job!

**Comment by toncho11** [comment]
So  COLOR, DRAW, CIRCLE will work only on NEC PC-98?

**Comment by tyama501** [comment]
Hello @toncho11 ,

Now these only work for PC-98.
We welcome someone writes codes for IBM.

**Comment by cocus** [comment]
I have no knowledge on how the EGA/CGA/VGA modes work, otherwise I'd like to add some kind of support for the PC.

**Comment by ghaerr** [comment]
> on  how the EGA/CGA/VGA modes work, otherwise I'd like to add some kind of support for the PC.

The IBM PC will change video modes using INT 10 fn AH=0. Here's some [reference](https://stanislavs.org/helppc/int_10.html) on how that works, as well as other functions to write graphics pixels.

You're welcome to play around with it; @tyama501 has added the host_mode() and other callouts for these functions, which would need to be expanded in host-stubs.c. Let me know if you need help, if you decide to work on it.

**Comment by toncho11** [comment]
@tyama501 Have you already ported an existing basic game? For example [snake](http://www.quitebasic.com/prj/games/snake/)?

**Comment by tyama501** [comment]
Thank you @cocus , @ghaerr ,

Let's also modify the opening message of the basic before releasing 0.6.0 :)

**Comment by tyama501** [comment]
@toncho11 ,

No, not yet :)

**Comment by toncho11** [comment]
> Thank you @cocus , @ghaerr ,
> 
> Let's also modify the opening message of the basic before releasing 0.6.0 :)

In my previous message I put the the link of [snake source code](http://www.quitebasic.com/prj/games/snake/). You can try it. It uses only "plot" for graphics.

**Comment by toncho11** [comment]
In my previous message I put the the link of [snake source code](http://www.quitebasic.com/prj/games/snake/). You can try it. It uses only "plot" for graphics.

> @toncho11 ,
> 
> No, not yet :)

**Comment by tyama501** [comment]
Thanks @toncho11 ,

Interesting. I will try that later.
Maybe I need to draw bigger dot for PC-98
since screen is 640x400.

**Comment by toncho11** [comment]
> Thanks @toncho11 ,
> 
> Interesting. I will try that later. Maybe I need to draw bigger dot for PC-98 since screen is 640x400.

The web-site I provided is using "Quite BASIC". Here is the [documentation](http://www.quitebasic.com/help/).

**Comment by ghaerr** [comment]
> I put the the link of [snake source code](http://www.quitebasic.com/prj/games/snake/). You can try it. It uses only "plot" for graphics.

A quick review of the snake source shows that ELKS BASIC is close, but not quite ready to port this game. We still don't support keyboard input, and, since there is no BASIC standard, the entire game source will have to be manually ported. We don't use the square brackets for arrays, but a DIM integer array could work. There is also the problem that the snake display requires a much less-dense display than 640x400, which the PC-98 has. Thus there will be a need for a CGA-style graphics mode, since the array G requires one entry per pixel and we have nowhere near that much memory in ELKS BASIC.

All-in-all, a good and fun project for enhancing BASIC with a number of new features, but still quite a bit of work.

**Comment by tyama501** [comment]
Hello @ghaerr , @toncho11 

I ported the snake except the get key part.

I used CIRCLE instead of PLOT. CIRCLE is moving like snake.

snake

Is there any idea how to get INKEY$ working?

```
100 REM port from www.quitebasic.com/prj/games/snake
200 MODE 1
300 CLS 
400 PRINT "=== Snake and Dots ==="
500 PRINT "UP: W"
600 PRINT "DOWN: Z"
700 PRINT "LEFT: A"
800 PRINT "RIGHT: S"
850 DIM G(625)
900 REM === Initialize ===
910 COLOR 1,0
920 PLOT 0,0
930 DRAW 240,0
935 DRAW 240,240
940 DRAW 0,240
945 DRAW 0,0
950 F=0
1000 P=12
1010 Q=12
1020 G(P+Q*25)=1
1030 COLOR 4,0
1040 CIRCLE P*10,Q*10,5
1050 R=12
1060 S=11
1070 G(R+S*25)=1
1080 CIRCLE R*10,S*10,5
1085 COLOR 6,0
1090 G(20+20*25)=5
1100 CIRCLE 20*10,20*10,5
1110 REM === Keyboard input ===
1120 C$=INKEY$
1130 IF C$="W" OR C$="w" THEN G(P+Q*25)=1
1140 IF C$="Z" OR C$="z" THEN G(P+Q*25)=2
1150 IF C$="A" OR C$="a" THEN G(P+Q*25)=3
1160 IF C$="S" OR C$="s" THEN G(P+Q*25)=4
1170 REM === Move the snake ===
1180 D=G(P+Q*25)
1190 GOSUB 9000+100*G(P+Q*25)
1200 P=P+U
1210 Q=Q+V
1220 IF P>24 OR P<0 OR Q>24 OR Q<0 THEN GOTO 7000
1230 IF G(P+Q*25) THEN GOTO 3000
1240 G(P+Q*25)=D
1250 COLOR 4,0
1260 CIRCLE P*10,Q*10,5
1270 D=G(R+S*25)
1280 GOSUB 9000+100*G(R+S*25)
1290 G(R+S*25)=0
1300 COLOR 0,0
1310 CIRCLE R*10,S*10,5
1320 R=R+U
1330 S=S+V
1340 PAUSE 500
1350 GOTO 1110
3000 REM Collision detection
3010 IF G(P+Q*25)<=4 THEN GOTO 7000
3020 F=F+1
3040 PRINT "=== Snake and Dots ==="
3050 PRINT "Score: ",F
3060 G(P+Q*25)=D
3070 COLOR 4,0
3080 CIRCLE P*10,Q*10,5
3090 REM Add a new dot
3100 A=INT(RND*24)
3110 B=INT(RND*24)
3120 IF G(A+B*25) THEN GOTO 3060
3130 COLOR 6,0
3140 CIRCLE A*10,B*10,5
3150 G(A+B*25)=5
3160 GOTO 1130
7000 REM === Game Over ===
7010 PRINT "=== Snake and Dots ==="
7020 PRINT "      Game Over"
7030 PRINT "Total score: ",F
7040 IF F<5 THEN PRINT "- Ouch!"
7050 IF F>=5 AND F<15 THEN PRINT "- Nice Try!"
7060 IF F>=15 AND F<50 THEN PRINT "- Way to go!"
7070 IF F>=50 AND F<250 THEN PRINT "- Great score!"
7080 IF F>=250 THEN PRINT "-- Amazing score!"
7090 PRINT "======================"
7100 STOP 
9000 REM Subroutines mapping the direction number
9100 U=0
9110 V=1
9120 RETURN 
9200 U=0
9210 V=-1
9220 RETURN 
9300 U=-1
9310 V=0
9320 RETURN 
9400 U=1
9410 V=0
9420 RETURN 
```
Thank you!

**Comment by tyama501** [comment]
One more thing. I forgot to do "sync" command after exiting basic and I could not save the file once. Maybe it is user friendly if sync with the save command.

**Comment by ghaerr** [comment]
Hello @tyama501,

> I ported the snake except the get key part.
> Maybe it is user friendly if sync with the save command.

Would you like to submit elkscmd/basic/snake.bas as a PR, even though INKEY$ is not implemented? (You could call RND for time being and have snake go randomly).  Also, you could add sync() to host.c::host_saveProgramToFile() after fclose() call.

> Is there any idea how to get INKEY$ working?

Yes - this has been on my list - we need to set stdin to raw mode and replace fgets calls to work in raw mode. Then INKEY$ can be implemented by attempting non-blocking read from stdin to check if character available. However, still a bit complicated because interpreter also needs to handle ^C to stop program execution; that could be handled by either checking with non-block read for ^C between each statement (which has the bad side effect of reading input data which probably needs to be pushed back and stored somewhere or perhaps discarded if not ^C), *or*, leave stdin in raw mode but allow ISIG signals, which could work by catching SIGINT and setting global variable, which would then be checked each statement. Which do you think would be better approach?

Thank you!

**Comment by tyama501** [comment]
Hello @ghaerr ,

>Would you like to submit elkscmd/basic/snake.bas as a PR, even though INKEY$ is not implemented? (You could call RND for time being and have snake go randomly). Also, you could add sync() to host.c::host_saveProgramToFile() after fclose() call.

Good idea. I will do this.

> that could be handled by either checking with non-block read for ^C between each statement (which has the bad side effect of reading input data which probably needs to be pushed back and stored somewhere or perhaps discarded if not ^C), or, leave stdin in raw mode but allow ISIG signals, which could work by catching SIGINT and setting global variable, which would then be checked each statement. Which do you think would be better approach?

Well, I don't know but it sounds straightforward using raw mode for $INKEY while running the program and use SIGINT to stop the program without killing Basic if possible.

**Pull request merged**
