### PR TITLE
Add nxtetris, added Nano-X GrGetNextEventTimeout, other bugfixes

### PR DESCRIPTION
**Pull request by ghaerr**
Adds `nxtetris` and `nxtest` to distribution when CONFIG_APP_OTHER=y set.

`nxtetris` was discussed a bit in https://github.com/jbruchon/elks/issues/871#issuecomment-1435875961, and can run without a mouse, using the s/d/j/k/space keys. The game speed can be increased or decreased using the +/- keys.

`nxtest` allows testing of the graphics drawing speed. It starts out drawing rectangles 10ms apart, but can be speed up or slowed down by using the +/- keys, up to a maximum speed quite faster than the original version.

Here's both files for testing without having to build:
[nxtetris.zip](https://github.com/jbruchon/elks/files/10778301/nxtetris.zip)

### CODE REVIEW

**Comment by toncho11** [comment]
@ghaerr Is it possible to hide the mouse pointer? I use only keyboard.

**Comment by ghaerr** [comment]
> Is it possible to hide the mouse pointer? I use only keyboard.

Yes, if you can confirm that you're using the `MOUSE_PORT=none` method of disabling mouse support. Otherwise, the pointer needs to remain visible.

How is the new game speed? I'm interested if it works well on older PCs. I ended up having to implement an event timeout scheme in Nano-X which synchronizes to clock time so that the speed should be the same on all systems.

**Comment by toncho11** [comment]
`export MOUSE_PORT=none` does not work in the sense that the mouse pointer is always there. I am not using the latest build of ELKS though.
The initial speed is fast for me. But I am able to slow it down with "-" and then it is quite playable :)
Thank you!
@tyama501 does it work for you?

**Comment by ghaerr** [comment]
> export MOUSE_PORT=none does not work in the sense that the mouse pointer is always there. 

I'm aware that the mouse pointer will always be visible - my question is: are you using `export MOUSE_PORT=none` in order to disable the mouse when you play the game on your PC? (This feature was requested by you some time back). I can't just remove the mouse pointer without associating it with a mechanism for mouse disablement. Otherwise, users with mice will not see the mouse pointer when they play.

**Comment by toncho11** [comment]
I do not have a mouse attached. Not having a mouse does not block the game from starting with or without `export MOUSE_PORT=none`. So it was not supposed to start without `export MOUSE_PORT=none`? #1502 

So, yes a possible improvement is when `export MOUSE_PORT=none` is to hide the mouse cursor and position the game in the center of the screen.

**Comment by ghaerr** [comment]
> Not having a mouse does not block the game from starting with or without export MOUSE_PORT=none. So it was not supposed to start without export MOUSE_PORT=none?

Yes, that's what I thought was agreed on. I seem to remember that at least one of your systems would not start Nano-X unless we set MOUSE_PORT=none. Nano-X won't be able to open the mouse if there is no serial card at /dev/ttyS0.

> yes a possible improvement is when export MOUSE_PORT=none is to hide the mouse cursor and position the game in the center of the screen.

Ok, will do both.

**Comment by toncho11** [comment]
I see. This computer has indeed a built-in serial card (Amstrad 1640) and that is why it does not require `export MOUSE_PORT=none`. The other one the IBM 5160 requires the `export MOUSE_PORT=none` as I do not usually put a serial card.

**Pull request merged**
