### PR TITLE
[cmds] Add Sinclair BASIC Interpreter

### PR DESCRIPTION
**Pull request by ghaerr**
This PR ports [ArduinoBASIC](https://github.com/robinhedwards/ArduinoBASIC) from an Arduino environment to ELKS, macOS and Linux. The interpreter is the same, but the host environment was changed quite a bit.

This BASIC language interpreter is very similar to [Sinclair BASIC](https://en.wikipedia.org/wiki/Sinclair_BASIC), and implements all the usual features, with float and string variables, multi-dimensional arrays, FOR-NEXT, GOSUB-RETURN, and a variety of useful functions. A quick overview of the language implemented is at elkscmd/basic/README.md.

It supports execution by typing in commands (with or without line numbers) in immediate mode, as well as from a file via command line argument. SAVE/LOAD are not yet implemented from within. All numeric computation is done via floating point, and uses the new C library float routines to do so (yes, quite a few issues were found).

All input is tokenized into a statically-allocated buffer, which also includes all space for variables, arrays, strings and numbers. This buffer is currently set to 10K and uses byte opcodes, so it is well suited to embedded applications, such as those @cocus has been requesting.

Despite the use of floating point throughout, very few math functions are implemented (only `floor` for BASIC's `INT()`, as each are currently being hand-crafted to keep things small and simple. Enhancements will be forthcoming.

Select CONFIG_APP_BASIC in make menuconfig in order to add `basic` to the filesystem (for ROMFS), this should default to ON for 1200K disks and larger.

Here's a quick look at running the executable, which uses about 26K on disk and 48K RAM:
Screen Shot 2022-04-06 at 6 17 34 PM

Have fun!

### CODE REVIEW

**Comment by cocus** [comment]
Amazing! I was going to start working on this port, but you beat me by a couple of thousand of miles. Runs pretty good!

```
# basic
Sinclair BASIC
10240 bytes free

100 for i=3 to 6 step 0.5
200 print i; "   "; int(i)
300 next i
run
3   3
3.5   3
4   4
4.5   4
5   5
5.5   5
6   6
mem
10149 bytes free
```

**Comment by ghaerr** [comment]
Cool! Is that running on your embedded 8081x system?

Let me know what additional (math or other) functions you might be interested in; it's been interesting learning  about gcc's floating point support, and putting together libc support from scratch. I found a bunch of Sinclair Basic programs and was thinking of enhancing this to get them running, if only to learn more about float math implementations.

Are you thinking of using BASIC to control any 8018x hardware, or just running it over the serial port for computations?

**Comment by cocus** [comment]
> Cool! Is that running on your embedded 8081x system?

Yes it is! In fact, I'm running it thru telnet. I've added support for the PIN and PINREAD so it can write directly to the 8 LEDs this thing has. I'm having so much fun!



> Let me know what additional (math or other) functions you might be interested in; it's been interesting learning about gcc's floating point support, and putting together libc support from scratch. I found a bunch of Sinclair Basic programs and was thinking of enhancing this to get them running, if only to learn more about float math implementations.

Cool! Yeah I didn't dive so deep as to understand the floating point stuff, I remember that when I created my own PC BIOS I had a lot of trouble with the integer math, so I don't even want to think about the floats :) 



> Are you thinking of using BASIC to control any 8018x hardware, or just running it over the serial port for computations?

Yes, at least on this platform, I can toggle the LEDs, and read an 8 bit dip switch. I think it'd be fun to add POKE/PEEK, or maybe IN/OUT (those would be a little bit more "safe" than letting the program modify any address on the system).

What do you think?

**Comment by ghaerr** [comment]
> I've added support for the PIN and PINREAD so it can write directly to the 8 LEDs this thing has. I'm having so much fun!

I had a lot of fun porting it as well :) Very cool about PIN/PINREAD - perhaps you should split those host_xxx functions out of host.c and put them into a machine-specific file for your system. We will need to think up a way for the functions to be disabled for non-8018x systems, although the easiest at first might be to put them into a seperate file, then include <linuxmt/config.h> and ifdef CONFIG_ARCH_8018X for the time being (or perhaps just compile in a completely seperate .c file controlled via Makefile). We should try to keep both a generic version and 8018X (or other platform) compilable and running at the same time.

> at least on this platform, I can toggle the LEDs, and read an 8 bit dip switch. I think it'd be fun to add POKE/PEEK, or maybe IN/OUT 

That sounds great, send some PRs! My only advice would be to check with the original Sinclair manual (link above) to see what the original syntax was (if any), and implement that to be compatible. And also call out of the interpreter using new host_xxx routines so that basic.c stays completely system independent. Definitely want to see a video of your blinkenlights lol!! :)

I'll stay oriented around missing mainstream enhancements, like READ, DATA, RANDOMIZE, and also want to get INKEY$ working and a way for ^C to abort interpreter execution, but stay in BASIC. I put a TODO file in elkscmd/basic/TODO for stuff I think would be neat to add.

**Comment by cocus** [comment]
> I had a lot of fun porting it as well :) Very cool about PIN/PINREAD - perhaps you should split those host_xxx functions out of host.c and put them into a machine-specific file for your system. We will need to think up a way for the functions to be disabled for non-8018x systems, although the easiest at first might be to put them into a seperate file, then include <linuxmt/config.h> and ifdef CONFIG_ARCH_8018X for the time being (or perhaps just compile in a completely seperate .c file controlled via Makefile). We should try to keep both a generic version and 8018X (or other platform) compilable and running at the same time.
> 
> >

That could be nice. In general I think the PIN, PINMODE and READPIN can be used on a 8018x CPU since it has a lot of pins that could (potentially) be used as GPIOs (as on Arduinos). However, in my particular design, I'm using some of them to bitbang the SD card, and one of them as a "general chip select" (i.e. when a specific memory region is accessed, it'll directly generate the CS signal for that peripheral), so it could be a little bit dangerous to change the functionality of these willy-nilly. But if they're available on any given design, then it should be fine to use them.
In my case, the LEDs are NOT connected there, but rather mapped in IO (using one of these general chip select pins), so writing a byte into IO will change the LEDs status. I'm using PIN to set them just for giggles, but it would only make sense on this particular design, not on any generic 8018x board.



> That sounds great, send some PRs! My only advice would be to check with the original Sinclair manual (link above) to see what the original syntax was (if any), and implement that to be compatible. And also call out of the interpreter using new host_xxx routines so that basic.c stays completely system independent. Definitely want to see a video of your blinkenlights lol!! :)

I'll do. I think the original Sinclair basic had some peek/poke commands, but I'll double check.




> I'll stay oriented around missing mainstream enhancements, like READ, DATA, RANDOMIZE, and also want to get INKEY$ working and a way for ^C to abort interpreter execution, but stay in BASIC. I put a TODO file in elkscmd/basic/TODO for stuff I think would be neat to add.

Cool! Yeah, probably writing the tokenized basic file into a .bas file would be cool as well. I remember old basic interpreters that did this instead of having the plaintext basic source.

**Comment by ghaerr** [comment]
> Yeah, probably writing the tokenized basic file into a .bas file would be cool as well. I remember old basic interpreters that did this instead of having the plaintext basic source.

In our case, BASIC immediately tokenizes input plaintext source code (from a command line arg or typed in with a line number), and then re-creates the source from the token array (mem[]) when you LIST it (you'll see everything gets capitalized, etc). The original source is thrown away. So a very easy SAVE command would just LIST to a file to get plaintext. There may be cases where we want to save the tokenized version, but only in deeply embedded environments, since the interpreter can easily retokenize on input.

Lots of fun to be had. What I'd like to see is some more complex already-written programs running. Another guy Paul Dunn who wrote a full-blown [Sinclair BASIC lookalike called SpecBAS](https://github.com/ZXDunny/SpecBAS) has posted a huge bunch of programs [here](https://github.com/ZXDunny/SpecBAS-Demos). I considered starting with his interpreter but it's written in Pascal. I'm going to deep dive a bit more into his and the original Sinclair BASIC language.

**Comment by cocus** [comment]
> Definitely want to see a video of your blinkenlights lol!! :)

Please feel free to have a look at this video I just created. I'm using "load/save" with the tokenized memory, like the original source did with an external EEPROM (I've implemented the dir command as well :) ): https://www.youtube.com/watch?v=XvHsd9JyTIc
(And I've also implemented the delay() function using usleep)

**Comment by ghaerr** [comment]
Wow Santiago you're on fire!!!!! That is so cool and I'm very pleased to see you take this and run with it. I spent most of the day working on getting it going, and now looks like you've very quickly pulled together the loose ends :)

Make sure to post a PR with all your new goodies!!! I'll stay away from any changes for a bit... I'm deep trying to find a lightweight C math library for it and ELKS, with no luck so far.

Here's a [Sinclair Reference Manual](https://worldofspectrum.net/ZXBasicManual/index.html) I just found you might find interesting.

I'm really holding back thinking about how much fun it would be adding graphics PLOT/DRAW...

**Comment by cocus** [comment]
> I'm really holding back thinking about how much fun it would be adding graphics PLOT/DRAW...

That'd be nice, for those with a graphics adaptor :) For me it's going to be character stuff for the time being. Maybe my new SBC based on this design will be able to talk to a GLCD or a TFT display, but that'll take time. For now, maybe PC users would benefit from any plot or draw commands.



> Make sure to post a PR with all your new goodies!!! I'll stay away from any changes for a bit... I'm deep trying to find a lightweight C math library for it and ELKS, with no luck so far.

Yes, I'm thinking of commiting and opening a PR with the LOAD/SAVE/DIR changes, since we'd all benefit from these. Even if the files are not plaintext, but... it's a start!

**Comment by ghaerr** [comment]
> I'm thinking of commiting and opening a PR with the LOAD/SAVE/DIR changes,

Heck yeah!

> Even if the files are not plaintext, but... it's a start!

No worries, looks like that's how the Arduino version did it. Include your PIN/PINMODE stuff too, if you're dragging in anything not portable to the IBM PC build, perhaps just ifdef that in to the Makefile or host.h header for the time being. Otherwise, just leave it all enabled if possible, and I'll try not to execute a PIN statement on the PC lol!

I'm not sure anybody really cares about PLOT/DRAW, so I'll leave that all be for a bit. Learning about the implementation of floating point to get this ported has captured my interest, and this would be a good time to get a tiny libc math library so I think I'll keep going in that direction.

**Comment by toncho11** [comment]
Hi,

I am new to Sincalair.
Here is a list of games for "SINCLAIR BASIC": https://spectrumcomputing.co.uk/index.php?cat=999&group_id=4002.
Having all these games all of a sudden will be exciting! :)

**Comment by ghaerr** [comment]
Hello @toncho11,

Thanks for the list of Sinclair BASIC games.

> Having all these games all of a sudden will be exciting! :)

Yes, it could be :) We're not quite there yet though, as other than the bare-bones interpreter, we're kind of building all of this up from scratch, starting with even getting floating point routines working. The games will require some code to put the PC into graphics modes, along with a CGA or EGA driver, which we could port from nano-X. There are also some issues with "Sinclair BASIC" source code compatibility. But it's a start!

Thank you!

**Comment by toncho11** [comment]
Good job!!!
Thank you!

**Comment by astrobleem** [comment]
image

awesome

**Comment by ghaerr** [comment]
Yes @astrobleem, be careful... you might be psychoanalyzed by a 1985 AI professor lol.

We're having some fun adding enhancements to the recently added BASIC interpreter... join in on the fun if you like!

**Pull request merged**
