### PR TITLE
Last past of sash cmd history implemented.

### PR DESCRIPTION
**Pull request by Mellvik**
Added history search (`!ls` etc.), recall last arg from previous command (`!$`) and support for history commands anywhere on the command line.

### CODE REVIEW

**Comment by ghaerr** [comment]
I'll have to give this a test, thanks.

No big deal, but functions (cmd_search, fixbuf, etc) in "library" code that are linked to other applications (like sash, in this case), should probably be declared static so that its obvious they aren't called outside the implementation, and won't possibly interfere when reused elsewhere.

**Comment by Mellvik** [comment]
OK, makes sense. I'll fix that along with a fix for a (new) bug I just found in the command edit function (^old^new).

I also want to take a look at the SIGINT problem we discussed before.

--Mellvik

**Comment by ghaerr** [comment]
> I also want to take a look at the SIGINT problem we discussed before.

Are you talking about trying to get the sash prompt displaying properly after an interrupt in all cases? I looked into that and I don't think an easy fix is possible, without using `setjmp`, which is a lot of trouble. I'm interested if you find a simpler solution.

**Comment by ghaerr** [comment]
@Mellvik, I just noticed that the compilation of your cmd_history file is spitting out a number of warnings, all of which should be looked into. This should be standard procedure when compiling new code. This can be made easier amidst the mess of elkscmd/ warnings by compiling within elkscmd/sash initially, rather than with a full make.

**Pull request merged**
