### PR TITLE
[libs/string] Correction of makefile and strspn.

### PR DESCRIPTION
**Pull request by marcin-laszewski**

### CODE REVIEW

**Comment by marcin-laszewski** [comment]
Do you know what is wrong with this problem?
Does it touch building process or source code I have sent?

**Comment by ghaerr** [comment]
@marcin-laszewski, perhaps the 'Merge branch master into string' should have been done differently on your side? The actual source changes you're making look fine.

**Comment by mfld-fr** [comment]
Transient CI failure - Ask @jbruchon to retry the pipeline (I have no more access to do it) or push a dummy commit to restart another one.

**Comment by jbruchon** [comment]
I'm on it!

**Pull request merged**
