### PR TITLE
Portability fixes for MSDOS filesystem; Minix floppy boot fixup; ctype.h for tolower()

### PR DESCRIPTION
**Pull request by fonin**
I had to fix certain minor things while tried to build the system for Poisk-1 soviet XT clone.
All issues are related to MSDOS code.
Not quite sure about ctype.h and io.h (were #error pragmas added intentionally?)

### CODE REVIEW

**Comment by mfld-fr** [comment]
Hello @fonin, just to tell you that your PR is taken into account, but its processing would be delayed because I am on holidays. Stay tuned !

**Comment by fonin** [comment]
@mfld-fr all right, me on vacation as well) take a good time)

**Comment by mfld-fr** [comment]
Back from holidays, starting the review...

**Comment by mfld-fr** [comment]
Thanks for your contribution !

**Comment by fonin** [comment]
> 
> 
> Thanks for your contribution !

More to go :) although, not right now.

**Pull request merged**
