### PR TITLE
minix file system documention

### PR DESCRIPTION
**Pull request by georgp24**
Add a document describing the minix file system to the text files in the documentation directory.

### CODE REVIEW

**Comment by mfld-fr** [comment]
There is already a placeholder for that topic in the documentation:
`/Documentation/html/technical/Minix-File-System.html`

Maybe you should replace this placeholder by your new document.

**Comment by georgp24** [comment]
I can do that, I also have a html version of the document. Or I leave it as text and remove the placeholder with my commit.

Maybe Jody can mention what he would like.

**Comment by jbruchon** [comment]
If your new document explains the filesystem better, there is no reason to keep the old one. Personally I dislike HTML documentation but I also can see some value in it *IF* there are hyperlinks that connect stuff together in some logical way.

I'd be fine with migrating anything from the old document that's not present in the new one and still holds value, then nuking the old one entirely.

**Comment by mfld-fr** [comment]
Obviously Georg's new document has more added value than the old one:
```
<HTML>
<Head>

<Title>The Minix File System</Title>

</Head>
<Body BGColor=White Text=Black Link=Blue VLink=Blue ALink=Blue>

<H1 Align=Center>The Minix File System</H1>

<H2 Align=Center>As used by the ELKS Operating System</H2>

<P Align=Center>by <A HRef="MailTo:Riley@Williams.Name">Riley
Williams</A></P>

<P Align=Justify>This paper attempts to document the MINIX file system as
used by the <A HRef="http://elks.sf.net/">ELKS</A> operating system. It
was written because of the confusion amongst ELKS developers regarding
precicely how this file system worked, and what requirements it placed on
the tools that manage the file system.</P>

</Body>
</HTML>
```
Already did the cleanup for my next commit.

**Comment by jbruchon** [comment]
Yikes. I never actually looked at it. Now I'm glad I didn't.

Feel free to aggressively delete any "documentation" that is mostly useless.

**Comment by mfld-fr** [comment]
I am a bit frightened by your repeated usage of "aggressively" :-)

**Pull request merged**
