### PR TITLE
[kernel] Add XMS memory support for kernel buffers

### PR DESCRIPTION
**Pull request by ghaerr**
This is a first-draft set of commits implementing the ability to use memory above 1MB for kernel system buffers, freeing up space from main memory for application programs. Requires 386 or later and compatible A20 gate handling.

Tested and working on QEMU, with up to 256K in XMS buffers allocated.

More work is in process, before commit: SSD and RAM disk drivers need to be made compatible with changes, they won't work with XMS in this PR. Also will add debug output to `unreal16` for real hardware testing.

Unfortunately, we're running into a few problems supporting a large (e.g. > 256K) amount of kernel buffers in XMS memory. The reason is that the "buffer headers", a data structure header that points to the actual XMS buffer, must reside in the kernel data segment. Each buffer header is 26 bytes, which means that 26K of data would be used just to track 1MB of XMS buffers; we only have 64K total and there's only 8K to spare with 128K of XMS buffers. Not sure how to work this out, but still saves 64-128K+ of main memory on 386 PCs.

### CODE REVIEW

**Comment by ghaerr** [comment]
Hello @Mellvik, this is pretty much complete, but tested on QEMU only. I added debug statements to `unreal16` to help understand what is hanging on your hardware.

The build defaults to XMS support ON, and will allocate CONFIG_FS_NR_XMS_BUFFERS (default 128) if on a 386 and unreal mode and the A20 gate can be successfully turned on. If not, then the CONFIG_FS_NR_EXT_BUFFERS (default 64) is used, and the buffers are allocated in main memory. 

All block device drivers, including BIOS FD/HD, SSD-TEST and RAMDISK are tested and working, although SSD and RAMDISK still allocate out of main memory. That will be updated in another PR. @cocus, I've updated ssd-sd.c to use the new ramdesc_t physical ram descriptor type required for the buffer system now, and moved one __far pointer create further back into `sd_read` and `sd_write`. I'm unable to test, but I think it should work fine. Of course, the 8018X won't support any XMS or unreal mode.

Here's what `unreal16` should look like on success:
Screen Shot 2021-11-09 at 6 43 00 PM

If your system doesn't work with `unreal16`, XMS buffers likely won't get enabled by the kernel. Here's a boot screen showing the location of the "xms:" successful output early in the boot sequence:
Screen Shot 2021-11-09 at 6 51 42 PM

If your system doesn't work, let me know the make and model of the machine, to look up the A20 hardware.

**Comment by cocus** [comment]
@ghaerr I'll give it a shot as soon as I can!

**Comment by Mellvik** [comment]
Thank you @ghaerr - 

This helps.
I'm getting the xms: … message in front of the other boot messages as expected.

But the boot didn't get very far. Maybe the point where it stopped may give you a clue?


Direct console, scan kbd 80x25 emulating ANSI (3 virtual consoles)
ttyS0 at 0x3f8, irq 4 is a 16450
ttyS1 at 0x2f8, irq 3 is a 16550A
ttyS2 at 0x3e8, irq 5 is a 16550A
eth: NE2K at 0x300, irq 12, MAC 00:80:29:ef:d9:51
bioshd: hda BIOS CHS 610,16,63
bioshd: hda  IDE CHS 993,16,63
bioshd: 2 floppy drives and 1 hard drive
Partitions: hda:(0,1000944) 


As you can tell, I'm (always) using serial console, hardly ever being in the same room as the physical machine (except to change floppies etc.). BTW there is an explanation for the big difference in BIOS CHS and real CHS, that's a different story.

The normal boot process goes as follows:
———
Direct console, scan kbd 80x25 emulating ANSI (3 virtual consoles)
ttyS0 at 0x3f8, irq 4 is a 16450                            
ttyS1 at 0x2f8, irq 3 is a 16550A                           
ttyS2 at 0x3e8, irq 5 is a 16550A                           
eth: NE2K at 0x300, irq 12, MAC 00:80:29:ef:d9:51           
bioshd: hda BIOS CHS 610,16,63                              
bioshd: hda  IDE CHS 993,16,63                              
bioshd: 2 floppy drives and 1 hard drive                    
Partitions: hda:(0,1000944)  hda1:(63,997857)               
device_setup: BIOS drive 0x0, root device 0x380             
PC/AT class machine, Unknown x86 CPU, 640K base RAM.        
ELKS kernel 0.4.0 (50640 text, 12400 ftext, 7792 data, 44704 bss, 13038 heap)
Kernel text at 2c0:0000, ftext f1d:0000, data 1224:0000, top a000:0, 503K free
fd: found valid ELKS disk parameters on /dev/fd0 boot sector
fd: /dev/fd0 probably has 18 sectors, 2 heads, and 80 cylinders
VFS: Mounted root 0x0380 (minix filesystem).
Running /etc/rc.d/rc.sys script
Starting networking on eth
ktcp -b 10.0.2.15 10.0.2.2 255.255.255.0
ktcp: ip 10.0.2.15, gateway 10.0.2.2, netmask 255.255.255.0
ktcp: ethernet 00.80.29.ef.d9.51 mtu 1024
Starting daemons telnetd httpd 
ELKS built from commit 24ec88c0
Tue Nov 09 14:18:11 2021


ELKS 0.4.0

login: root
# ./ftpd -d
New Client Detected...
Child running.
-----------

Since the system is not booting, I don't get to test the unrea16 program.

Any changes I can make to the config to provide more clues?

—Mellvik

**Comment by ghaerr** [comment]
> Since the system is not booting, I don't get to test the unrea16 program.

What exact XMS message did the system give at boot? "xms: unreal mode and A20 gate enabled" ?

I am guessing that the kernel thinks A20 is enabled and it is not, although it does try to check it.

> Any changes I can make to the config to provide more clues?

Yes, please configure the system without CONFIG_FS_XMS_BUFFER and rebuild:
```
CONFIG_FS_EXTERNAL_BUFFER=y
CONFIG_FS_NR_EXT_BUFFERS=64
# CONFIG_FS_XMS_BUFFER is not set
# CONFIG_FS_NR_XMS_BUFFERS is not set
```
Then run `unreal16` and see what it says.

What is the make and model of your PC you're testing on?

**Comment by Mellvik** [comment]
@ghaerr,
> Since the system is not booting, I don't get to test the unrea16 program.
> 
> What exact XMS message did the system give at boot? "xms: unreal mode and A20 gate enabled" ?
> 
Yes, just double-checked it.
> I am guessing that the kernel thinks A20 is enabled and it is not, although it does try to check it.
> 
> Any changes I can make to the config to provide more clues?
> 
> Yes, please configure the system without CONFIG_FS_XMS_BUFFER and rebuild:
> 
> CONFIG_FS_EXTERNAL_BUFFER=y
> CONFIG_FS_NR_EXT_BUFFERS=64
> # CONFIG_FS_XMS_BUFFER is not set
> # CONFIG_FS_NR_XMS_BUFFERS is not set
> Then run unreal16 and see what it says.
> 
Report in the morning.
> What is the make and model of your PC you're testing on?
> 
Compaq portable 386/20, 10M ram. Will take closer look at hw configuration etc. tomorrow.

Thank you,

-M
>

**Pull request merged**
