### PR TITLE
[basic] Add sync() to host.c and porting snake.bas

### PR DESCRIPTION
**Pull request by tyama501**
Hello @ghaerr ,

I added sync() to the save command according to https://github.com/jbruchon/elks/pull/1286#issuecomment-1146429285

Also  snake.bas ported from www.quitebasic.com/prj/games/snake is added.
RND is uses instead of INKEY for now.

Thank you!

### CODE REVIEW

**Comment by tyama501** [comment]
Hello @ghaerr ,

Thank you for the merging.

Just for information.
It seems DosBox-X released 3 days ago supported LIO function.
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.84.0

I tried it and worked.
dosbox-X

**Comment by ghaerr** [comment]
> It seems DosBox-X released 3 days ago supported LIO function.
> I tried it and worked.

That is really cool!! I was just wondering this morning how I can run your snake program. I'll download v0.84 and try it out :)

**Comment by ghaerr** [comment]
Hello @tyama501,

I have your graphical snake program working over here! It is interesting how PC-98 graphics and text planes exist simultaneously. I am going to see if I can make snake program continue indefinitely, then add code for ^C and INKEY$ processing to BASIC.

Thank you!

**Comment by ghaerr** [comment]
If I change line 7000 to "7000 GOTO 1165" that allows the snake program to continue for a while automatically, but it seems snake head disconnected from rest of snake, and there are still portions of the snake that remain on screen, FYI.

It could be interesting to see DosBox-X LIO and GDC code for circle drawing for BIOS emulation, I am going to look at it, in case we want to implement functions on IBM PC platform:

https://github.com/joncampbell123/dosbox-x/blob/dosbox-x-v0.84.0/src/ints/pc98_lio.cpp

**Pull request merged**
