### PR TITLE
[basic] Add inp() and out() for both word and byte IO access

### PR DESCRIPTION
**Pull request by cocus**
Adds the INPB, INPW, OUTB and OUTW keywords for input and output
of bytes and words (8 and 16 bits).

### CODE REVIEW

**Comment by cocus** [comment]
@ghaerr please check if the additions to the basic-stubs.c are okay, or if I should remove them.

**Comment by cocus** [comment]
Next on the list would be a HEX$() which would be highly useful for the stuff I'm working on.

**Comment by ghaerr** [comment]
This looks great, thanks!

Can push an update to basic/README.md to update the documentation of the two new commands and two new functions? Both IN() and OUT are documented in the Not Yet Implemented sections and need to be separated into the byte and word functions you've added. This will allow us to keep track of our nicely expanding language!

**Comment by ghaerr** [comment]
> check if the additions to the basic-stubs.c are okay, or if I should remove them.

Looks good as you've done it.

**Comment by cocus** [comment]
> This looks great, thanks!
> 
> Can push an update to basic/README.md to update the documentation of the two new commands and two new functions? Both IN() and OUT are documented in the Not Yet Implemented sections and need to be separated into the byte and word functions you've added. This will allow us to keep track of our nicely expanding language!

Right, I forgot about this!

**Comment by ghaerr** [comment]
Also, please check whether the TKN_FMT_POST should be set in the following:
```
    {"INPB", 1|TKN_FMT_POST},
    {"INPW", 1|TKN_FMT_POST},
```
Leaving that in will cause a space to be output after the keyword, which I don't think you want in a function. Type the function into a statement then "LIST" to see.

Thanks!

**Comment by cocus** [comment]
> Leaving that in will cause a space to be output after the keyword, which I don't think you want in a function. Type the function into a statement then "LIST" to see.

Yes, that's true. Should I also remove them from the OUTB/OUTW?

**Comment by ghaerr** [comment]
> Should I also remove them from the OUTB/OUTW?

No, because those aren't functions, they are commands. Also remove the old IN() function from README.md. We're almost there!

**Comment by cocus** [comment]
> > Should I also remove them from the OUTB/OUTW?
> 
> No, because those aren't functions, they are commands. Also remove the old IN() function from README.md. We're almost there!

I didn't see any declaration of the IN() function, only OUT() which I've already modified.

**Comment by ghaerr** [comment]
> I didn't see any declaration of the IN() function

It's the 4th line from the bottom. Don't worry, we can catch that next round.

**Comment by cocus** [comment]
> > I didn't see any declaration of the IN() function
> 
> It's the 4th line from the bottom. Don't worry, we can catch that next round.

woops

**Pull request merged**
