### PR TITLE
bugfix: Add forgotten include file in DEBUG mode.

### PR DESCRIPTION
**Pull request by marcin-laszewski**

### CODE REVIEW

**Review by ghaerr — CHANGES_REQUESTED** [review]
Thanks for finding this. Can you remove the \#ifdef DEBUG around the header file and just include the header file, please? This will help reduce unneeded ifdefs.

**Comment by marcin-laszewski** [comment]
Yes, of course! But in my opinion it is ok:

- DEBUG flags indicates that we need 'stat.h' file in "debug mode" only.
- Checking this flag is faster than include and parse 'stat.h' each time.

Your decision.

**Comment by ghaerr** [comment]
> Checking this flag is faster than include and parse 'stat.h' each time.

The issue is not about compilation speed - but more importantly the philosophy of less \#ifdefs (more readability, no conditional compilation and associated issues). There are also no other cases where an ELKS header is included via \#ifdef.

Thank you!

**Comment by marcin-laszewski** [comment]
OK. Done.

**Pull request merged**
