### PR TITLE
[image] FAT image in .config

### PR DESCRIPTION
**Pull request by mfld-fr**
* Integrate FAT image in standard build
* Remove useless `knl` program
* 32-bit inode number as a visible option (for #303)

Problem: boot hangs with `fd1440.bin` (with FAT image option in `.config`) just after mounting root... while it succeeds with `fd1440-fat.bin`. I should have missed something ?..

Edit: no problem with MINIX image option.

Edit 2: problem solved with the help from @ghaerr.

### CODE REVIEW

**Comment by ghaerr** [comment]
First look: did you mean 'ifdef CONFIG_FAT_DEV' instead of CONFIG_IMG_DEV in line 64 of image/Makefile?

**Comment by ghaerr** [comment]
While you're at it, the MINIX build has consistently spat out an error on the following lines in image/Makefile:

```
    find $(DESTDIR) \
        -type d ! -name root -execdir chmod go+rx '{}' ';' -o \
        ! -type d ! -name .profile -execdir chmod go+r '{}' ';'
```

Now that we use the `mfs` tool to build images, can't we just delete that altogether?

**Comment by ghaerr** [comment]
I didn't see where you removed `knl` from .config or the build, good idea. Can you also remove it from image/Packages so I don't have to?

**Review by ghaerr — COMMENTED** [review]
I'm still new with Config: where are the new menuconfig options for CONFIG_IMG_MINIX and CONFIG_IMG_FAT?

**Comment by mfld-fr** [comment]
> First look: did you mean 'ifdef CONFIG_FAT_DEV' instead of CONFIG_IMG_DEV in line 64 of image/Makefile?

No, no, it is correct : CONFIG_IMG_DEV means "*the image format supports the special devices files*". So YES for MINIX and ROM, NO for FAT.

CONFIG_FS_DEV is to enable the FAT 'fake dev' mechanism. Will mean "*enable devfs*" in the future, so the name.

**Comment by mfld-fr** [comment]
> I'm still new with Config: where are the new menuconfig options for CONFIG_IMG_MINIX and CONFIG_IMG_FAT?

Sorry, did not catch the question ?

**Comment by ghaerr** [comment]
> > First look: did you mean 'ifdef CONFIG_FAT_DEV' instead of CONFIG_IMG_DEV in line 64 of image/Makefile?
> 
> No, no, it is correct : CONFIG_IMG_DEV means "_the image format supports the special devices files_". So YES for MINIX and ROM, NO for FAT.
> 
> CONFIG_FS_DEV is to enable the FAT 'fake dev' mechanism. Will mean "_enable devfs_" in the future, so the name.

Confusing, but I get it now.

I was thinking that the reason the boot may be failing was that the /dev entries were not present on the FAT filesystem. I updated /bin/init to give decent error messages when it can't open various /dev files... what other process does the kernel do after mounting the root filesystem but before running /bin/init? Perhaps also run `mdir` on fd1440.bin and take a quick look at it.

**Comment by ghaerr** [comment]
> > I'm still new with Config: where are the new menuconfig options for CONFIG_IMG_MINIX and CONFIG_IMG_FAT?
> 
> Sorry, did not catch the question ?

I don't understand Config yet: Where are the questions in config.in that `menuconfig` asks for the above new options? That would allow me to see what is being asked and defaulted. Same for my confusion with CONFIG_IMG_DEV and CONFIG_FAT_DEV: I didn't see the code in `menuconfig` for those entries (I realize they are in various config.in files in the appropriate directories).

**Comment by ghaerr** [comment]
Just thought of the likely problem: The directory /dev must be created in fatfs:, and be within the first two directory entries for the 'automatic' CONFIG_FAT_DEV to work. I did this initially to avoid creating a /dev system on in-the-wild disks that happened to have a /dev in them. I can rewrite that check to something different if this proves problematic, but I think running an `mmd -i ... /dev` after the `mcopy -i ... ::/linux` will solve the problem.

**Comment by mfld-fr** [comment]
Yeah, it works with your '/dev' trick :smiley: ! Thank you !

**Comment by mfld-fr** [comment]
> While you're at it, the MINIX build has consistently spat out an error on the following lines in image/Makefile:
> 
> ```
>     find $(DESTDIR) \
>         -type d ! -name root -execdir chmod go+rx '{}' ';' -o \
>         ! -type d ! -name .profile -execdir chmod go+r '{}' ';'
> ```
> 
> Now that we use the `mfs` tool to build images, can't we just delete that altogether?

I remember these lines were added by @tkchia in https://github.com/elks-org/elks/pull/227.

**Pull request merged**
