### PR TITLE
[rom] Add capability to add applications by rom image size

### PR DESCRIPTION
**Pull request by ghaerr**
Adds enhancements to ROM filesystem application selection discussed in https://github.com/jbruchon/elks/pull/1279#issuecomment-1118058473.

Adds ability to run normal ELKS system in ROM, with full /bin/init startup, /etc/rc.sys processing, /bin/getty, /bin/login and selection of default shell (ash or sash). Lots of useful commands are added, such as clock, shutdown, uname, date, ps, meminfo, more, uptime and reboot.

Applications can be selected based on ROM size, using tags :128k (base system), or add BASIC and stty using :192k, and finally networking using ":net". Individual applications can be easily added or subtracted by editing elkscmd/Applications and/or changing the new CONFIG_APP_ROM_TAGS option in .config.

A new CONFIG_APP_ROM_TAGS= option is added to 8018x.config, emu86-rom-full.config and emu86-rom.config, which specifies the ROM size to build for, and which applications to include. For 8081x, the default setting is CONFIG_APP_ROM_TAGS=":ash|:128k|:192k|:net|" (everything).

I wasn't able to test more than a 128k ROM on emu86 as the IBM PC emulated architecture does not have enough space for a larger ROM.

Tested on 128k ROM using emu86-rom-full.config and `emu86`. Following is "ls -lR /" output:
```
Gregs-MBP1:emu86 greg$ ./es
info: load address E0000h
info: load file ../elks-gh/elks/arch/i86/boot/Image
info: file size=10000h
success: file loaded
info: load address 80000h
info: load file ../elks-gh/image/romfs.bin
info: file size=1ED29h
success: file loaded

ELKS Setup Headless console
32 ext buffers, 32768 ram
PC/AT class machine, NEC V20 CPU, 512K base RAM.
ELKS kernel 0.5.0 (55472 text, 0 ftext, 6576 data, 41136 bss, 17822 heap)
Kernel text at e062:0000, data c0:0000, top 8000:0, 445K free
VFS: Mounted root 0x0600 (romfs filesystem).
Running /etc/rc.sys script
Tue Jan 11 22:43:45 2011  <--- NOTE: clock command not working on IBM PC ROM emulator!! :)


ELKS 0.5.0

login: root
# ls -lR /

/:
dr-xr-xr-x  1 root     root          159  Jan  1 1970  bin
-r-xr-xr-x  1 root     root          447  Jan  1 1970  bootopts
dr-xr-xr-x  1 root     root          316  Jan  1 1970  dev
dr-xr-xr-x  1 root     root          121  Jan  1 1970  etc
dr-xr-xr-x  1 root     root            9  Jan  1 1970  home
dr-xr-xr-x  1 root     root            9  Jan  1 1970  mnt
dr-xr-xr-x  1 root     root            9  Jan  1 1970  root
dr-xr-xr-x  1 root     root            9  Jan  1 1970  tmp

/tmp:

/root:

/mnt:

/home:

/etc:
-r-xr-xr-x  1 root     root          464  Jan  1 1970  group
-r-xr-xr-x  1 root     root           89  Jan  1 1970  hosts
-r-xr-xr-x  1 root     root          493  Jan  1 1970  inittab
-r-xr-xr-x  1 root     root           13  Jan  1 1970  issue
-r-xr-xr-x  1 root     root         1004  Jan  1 1970  mount.cfg
-r-xr-xr-x  1 root     root          962  Jan  1 1970  net.cfg
-r-xr-xr-x  1 root     root          785  Jan  1 1970  passwd
-r-xr-xr-x  1 root     root         3503  Jan  1 1970  perror
-r-xr-xr-x  1 root     root          174  Jan  1 1970  profile
-r-xr-xr-x  1 root     root          657  Jan  1 1970  rc.sys
-r-xr-xr-x  1 root     root           73  Jan  1 1970  sashrc
-r-xr-xr-x  1 root     root          942  Jan  1 1970  termcap

/dev:
[...skipped...]

/bin:
-r-xr-xr-x  1 root     root         1216  Jan  1 1970  cat
-r-xr-xr-x  1 root     root         4272  Jan  1 1970  clock
-r-xr-xr-x  1 root     root         3056  Jan  1 1970  date
-r-xr-xr-x  1 root     root         5920  Jan  1 1970  getty
-r-xr-xr-x  1 root     root         7456  Jan  1 1970  init
-r-xr-xr-x  1 root     root         6976  Jan  1 1970  login
-r-xr-xr-x  1 root     root        11104  Jan  1 1970  ls
-r-xr-xr-x  1 root     root         4528  Jan  1 1970  meminfo
-r-xr-xr-x  1 root     root         3440  Jan  1 1970  more
-r-xr-xr-x  1 root     root         1886  Jan  1 1970  net
-r-xr-xr-x  1 root     root          576  Jan  1 1970  printenv
-r-xr-xr-x  1 root     root         6992  Jan  1 1970  ps
-r-xr-xr-x  1 root     root         2736  Jan  1 1970  pwd
-r-xr-xr-x  1 root     root         1296  Jan  1 1970  reboot
-r-xr-xr-x  1 root     root          992  Jan  1 1970  setup
-r-xr-xr-x  1 root     root        48848  Jan  1 1970  sh
-r-xr-xr-x  1 root     root         1264  Jan  1 1970  shutdown
-r-xr-xr-x  1 root     root         2087  Jan  1 1970  sys
-r-xr-xr-x  1 root     root          640  Jan  1 1970  uname
lr-xr-xr-x  1 root     root            3  Jan  1 1970  uptime -> ps
# uname -a   <-- @cocus here's how you get the full build information on ROM systems now
ELKS elks 0.5.0 commit 787930be 04 May 2022 23:40:33 -0600 ibmpc i8086
# ps
  PID   GRP  TTY USER STAT CPU  HEAP  FREE   SIZE COMMAND
    1     1   1 root    S   0  3072  2016  12960 /bin/init 
    6     6      root    S   2  1158  9130  64672 -/bin/sh 
    9     6      root    R   5  1024  1176  11744 ps 
# 
```
@cocus: I am not able to test the 8018x version on emu86, hopefully it will work fine. There is a chance that /bin/getty might interact with /etc/inittab incorrectly and interfere with the serial line you're running on. Should this happen, all of the /bin/init startup can be eliminated by removing the ':128k' from the following line in elkscmd/Applications (or /etc/inittab edited instead):
```
sys_utils/init          :boot   :sysutil    :128k
```

### CODE REVIEW

**Comment by ghaerr** [comment]
@cocus, I just realized that your 8018x port has SSD, so you'll want the ability to mount/umount as well as all the disk I/O commands. The :128k tag was created with read-only memory in mind. 

I've pushed another commit that adds file utils and disk utils, which including BASIC and KTCP is just under 384k.

**Comment by cocus** [comment]
Whoa that's amazing! I think that the 128k although interesting, should have the mount command (of course, if possible) so you can bootstrap it to another media, or mount another media with your apps. It was the scenario I had, where my apps were on the SD card and I rarely changed the ROMFS. But it's okay :)
So should I select the 384k one right?

Also, as a side note, I was thinking about how could we integrate my loader for the 8018x into ELKS so it produces a raw image that you can flash on an eeprom/flash directly, instead of going thru the paces of having another project to combine the romfs, kernel, loader.

I'll give this a try later today!

**Comment by ghaerr** [comment]
>  I think that the 128k although interesting, should have the mount command 

It already does, I added mount/umount in a second commit.

> So should I select the 384k one right?

It's all ready to go and included in your 8018x.config file: `CONFIG_APP_ROM_TAGS=":ash|:128k|:192k|"`, along with the CONFIG_APP_DISK_UTILS, CONFIG_APP_FILE_UTILS, CONFIG_APP_KTCP and CONFIG_APP_BASIC. Total just less than 384k.

> I was thinking about how could we integrate my loader for the 8018x into ELKS so it produces a raw image that you can flash on an eeprom/flash directly

Take a look at image/Makefile.image target "romfs:". Another label could be created that post-processes the romfs.bin image. That should probably go in another Makefile.xxx though, as things are already pretty complicated in the existing image Makefiles.

**Comment by cocus** [comment]
Okay, this is pretty cool! Now I can use this like if it was my Linux desktop!
However, there's something that doesn't seem to work. I can't seem to mount my SD card into /mnt:
```
# mount /dev/ssd /mnt
# cd /mnt
# pwd
/mnt
# ls
bin       bootopts  dev       etc       home      mnt       root      
tmp       var
# mount
          (romfs) blocks      0 free      0 mount /
/dev/ssd  (romfs) blocks      0 free      0 mount /mnt
```
But I do see the SSD driver recognizing my 2G card:
`ssd: 1977614336K disk`

**Comment by cocus** [comment]
Oh, I've figured I need to pass the `-t` to mount now:
`mount -t fat /dev/ssd /mnt`
Excellent!

**Comment by ghaerr** [comment]
> Okay, this is pretty cool! Now I can use this like if it was my Linux desktop!

Thanks, I figured you'd enjoy it once we got more of the cool utilities on ROMFS. I think yours is the first non-emulated real hardware to actually run a full ELKS in ROM! We've come a long way, thanks for your help!

> Oh, I've figured I need to pass the -t to mount now:

Hmmm... the default (no option) is now -a, which means auto-mount by reading the superblock for filesystem type. I'm wondering why that isn't working.

Are you able to copy files and manipulate the SSD filesystem?

Was there any change required to boot your system on serial, from the pre-defined 8018x.config? If so, feel free to submit changes.

**Comment by cocus** [comment]
> Are you able to copy files and manipulate the SSD filesystem?

When mounting it with the `-t fat` option, yes. My SD is fat formatted.



> Was there any change required to boot your system on serial, from the pre-defined 8018x.config? If so, feel free to submit changes.

Nothing changed! It works as-is. I was trying to get the clock changes for the rtc and I'll need to add a new config, but besides that, it was unchanged.

As a side note, my RTC doesn't seem to be working properly, but I'm suspecting a bad chip.

**Pull request merged**
