### PR TITLE
[LD scripts] explicitly put relocations away from text & data, for intermediate ELF output

### PR DESCRIPTION
**Pull request by tkchia**
See https://github.com/tkchia/gcc-ia16/issues/73 .

### CODE REVIEW

**Comment by ghaerr** [comment]
Hello @tkchia,

Adding this change to `elks-medium.ld` seems to have no effect, the .rel.dyn relocs are in the same place: does the compiler toolchain have to be re-built, by chance? (As I mentioned, my application build is being done outside the ELKS tree).

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

There _should_ be no need to rebuild the toolchain.  If `ld.gold` is indeed still placing the `.rel.dyn` sections in an inconvenient place, then I am not sure why.  Does `ia16-elf-gcc -v -v -v` show the linker using the correct, updated linker script?

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Hmmm... it seems `ia16-elf-gcc` is using a copied linker script deep down in a cross/ subdirectory `.../lib/elkslibc/medium/`. Is there a way to override this in the command line for testing?
```
gcc -plugin-opt=-pass-through=-lgcc --script /Users/greg/net/elks-gh/cross/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/lib/elkslibc/medium/elks-medium.ld -m i386elks --defsym=_heap=0xffff -fuse-ld=gold -o nano -l:crt0.o -Lncurses-5.2/lib/ -L/Users/greg/net/elks-gh/cross/lib/gcc/ia16-elf/6.3.0/elkslibc/medium -L/Users/greg/net/elks-gh/cross/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/lib/elkslibc/medium -L/Users/greg/net/elks-gh/cross/lib/gcc/ia16-elf/6.3.0 -L/Users/greg/net/elks-gh/cross/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/lib -Map=nano.map color.o cut.o files.o global.o move.o nano.o rcfile.o search.o utils.o winio.o regex.o -lncurses -lgcc -lc -lgcc -lgcc
```

[EDIT: Perhaps I should rebuild ELKS libc to get this copied correctly after modification?]

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

You can specify a `-T` _script_ option to `ia16-elf-gcc` to force using a particular linker script.

> [EDIT: Perhaps I should rebuild ELKS libc to get this copied correctly after modification?]

Good idea.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Thanks for your responses. I rebuilt ELKS libc and the updated `elks-medium.ld` linker script solves the original problem on https://github.com/tkchia/gcc-ia16/issues/73, so that can be closed, and this PR should be merged.

However - ELKS now refuses to load the resulting binary, which I think is correctly built, saying:
```
ELKS 0.4.0

login: root
# ./nano
./nano: not enough memory
# chmem nano
 TEXT   DATA    BSS   HEAP  STACK  TOTDATA  TOTAL
53264   8912   7840  65535      0    65520 118784 nano
# 
```
(I'm not able to update your chmem fix just yet).
I've attached that binary to help debug the kernel exec() routine, where I suspect the problem lies. Unfortunately, my ELKS tree has quite a few other changes required for the nano port for me to immediately investigate. I may commit a first version of nano in order to clean things up to look further into this next problem.

[nano.zip](https://github.com/jbruchon/elks/files/6223264/nano.zip)


Thank you!

**Review by ghaerr — APPROVED** [review]

**Comment by tkchia** [comment]
Hello @ghaerr,

Thanks!  Hopefully there can be some progress soon in getting a medium-model `nano` running.

**Comment by ghaerr** [comment]
Hello @tkchia,

I have "debugged" the memory problem and have found the issue: the system is working perfectly, the problem is now that we can compile and link large binaries, in some cases ELKS just doesn't have enough memory to run them (!!!).

With networking and multiuser serial console enabled, ELKS has 230k RAM available (not necessarily contiguous). Running the "big" version of `nano`, which uses 34k extra code for regex to implement color syntax highlighting, requires 108k code, and requests 64k data (max heap). ELKS can't find the memory for the data segment. Running ELKS without networking leaves 342k available, and nano runs:
Screen Shot 2021-03-29 at 11 16 46 AM

:) 

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

This is really cool.  Thanks!

**Comment by Mellvik** [comment]
Wow! This is big (pun intended).
To us on the outside, what this meanin practice?   I'm assuming larger applications, what are the new (real)  limits?
I just compiled the S editor, a tiny (and extremely fast) vi clone limited to in core data. Will this change allow more malloc space?

Thank you!
-M

**Comment by ghaerr** [comment]
Hello @Mellvik, nice to hear from you!

> To us on the outside, what this meanin practice?   I'm assuming larger applications, what are the new (real)  limits?

What it means is that a lot of the work done last year on medium model kernel, tool chain, libc and applications has now been shown to actually work by porting an early version of `nano` to ELKS. With a few of its features enabled, `nano` requires medium model to link; `nano` isn't small to ELKS!

However, porting arbitrary applications remains tricky, as larger in-the-wild applications can be very "loose" with RAM usage. For instance, `nano` uses the standard regular expression library (ported to ELKS at 34k) in order to implement syntax highlighting. That's just over half of our regular small-model code segment (64 KiB) used just for regular expression pattern matching. Medium model applications currently are allowed twice (128 KiB) as much code compared to small model, but the data segment is still limited to 64 KiB. And it appears that `nano` requires any edited file to reside in RAM; the regular expression syntax highlighting uses more data segment space reducing the maximum file size `nano` can edit.

> I just compiled the S editor, a tiny (and extremely fast) vi clone limited to in core data. Will this change allow more malloc space?

No, the data segment size is limited to 64 KiB in either small or medium model.

It is interesting to port various editors to ELKS. Porting `nano` has been on my list for months, since we realized that `kilo` requires large amounts of RAM compared to the size of the file being edited. I just ported Minix's editor `mined` to ELKS, it runs well, but few know it, and it's still limited to files that will fit within the data segment. So I thought porting `nano` might be useful. Much more work, as both libregex and libncurses-5.2 needed porting.  `nano` still only edits file in core, and uses file size + seven bytes per line additional RAM for housekeeping.

In addition, we're totally out of space on the default 1.44M floppy distribution. Neither `mined` nor `nano` will fit without removing `vi`, `fdtest` and a couple Nano-X programs. We're going to need to come up with a way to specify a person's favorite editor and/or slim down other programs on the standard distribution, and we could then accept `S` as well. I'd like to find an editor that will edit a 45k file (or so) and also display syntax highlighting.

Thank you!

**Comment by tkchia** [comment]
Hello @Mellvik,

> Wow! This is big (pun intended). To us on the outside, what this meanin practice? I'm assuming larger applications, what are the new (real) limits? I just compiled the S editor, a tiny (and extremely fast) vi clone limited to in core data. Will this change allow more malloc space? Thank you! -M

In brief, the medium memory model for ELKS now supports programs with
  * 128 KiB (actually 64 KiB + 64KiB) of code, and
  * 64 KiB of data.

The small memory model only supported
  * 64 KiB of code and
  * 64 KiB of data.

(ELKS's medium model is still not as powerful as the actual medium memory model supported by classical MS-DOS compilers --- which allow for more than two code segments, each 64 KiB --- but it should be useful.)

Thank you!

**Comment by Mellvik** [comment]
Thanks @tkchia, @ghaerr - that helps a lot.

Having jumped directly from Z80 to 68000/10/20/30 back in the days, I missed out on the segmentation issues and memory models (for better or worse), the update was much needed.

The answers brought up a couple of unrelated but associated (!) issues. One is that while nano with syntax highlighting etc. is a great test case in itself, I'm curious: in order to make a syntax highlighting editor useful on ELKS, we need a native compiler, right? Do either of you have something up your sleeve? I did look at the portable C compiler at some point last year, but put it aside for other priorities - and and thinking there must be other alternatives that are much better suited (and up to date) if we're moving in that direction.

The other issue is file compression - given the space issues on floppies. I've been missing gzip and zip on Elks, and put them next to tar(1) on my plate. Remembering my failure to get them to compile on Venix86 a few years back, I've not even tried on Elks. Now may be the time to revisit that part, enabling compressed tar files back and forth. Possibly even more relevant to the full floppy issue, maybe it is time to pull out the exomizer-discussion from a few years back, this time for 'from disk decrunching' only?

Thank you!

—Mellvik

**Comment by ghaerr** [comment]
Hello @Mellvik,

Regarding syntax highlighting in ELKS' editors - I must admit the exercise is mostly purely academic. The `nano` port started as a means of replacing `kilo`, which has syntax highlighting and shows well, even though there are currently no hosted C compilers. Porting editors has helped refine the requirements for the Direct and BIOS console drivers, which have required updating to support more common ANSI sequences to run the editors. And now adding syntax highlighting to nano is pushing the limits of our medium model application support. So it's mostly just putting ELKS through some real-word porting for the technical fun/testing of it :)

> maybe it is time to pull out the exomizer-discussion from a few years back, this time for 'from disk decrunching' only?

I'm not familiar with this discussion - are you talking about automatic file decompression managed by a filesystem?

Thank you!

**Comment by Mellvik** [comment]
Hi @Ghaerr,

yes, good to see you too! I guess the hiatus was well deserved after the pre-xmas-sprint. We've all had pending stuff to catch up on. Which in my case includes running the s editor on CPM.

Anyway - the discussion in which Exomizer was mention was this one 
https://github.com/jbruchon/elks/issues/226 <https://github.com/jbruchon/elks/issues/226>

in 2018. The idea is not file system related, but to compress the binaries and have them self-decompress at time of execution (which I gather is one of the modes of Exomizer) or possibly to have a separate decompressor being invoked by the kernel when encountering compressed binaries. 

I'm still not convinced it is a good idea given the limited resources of the typical target machine, but it may be an interesting discussion. Then again, if it is useful on 8-bit systems, it might just be useful here too.
I was not familiar with Exomizer until recently and was disappointed to find that it has not been ported to CP/M… However, there is something called PMexe supposedly working for CP/M, but that's outside the topic of this thread.

https://bitbucket.org/magli143/exomizer/wiki/Home <https://bitbucket.org/magli143/exomizer/wiki/Home>
https://en.wikipedia.org/wiki/Executable_compression <https://en.wikipedia.org/wiki/Executable_compression>

—Mellvik

**Comment by tkchia** [comment]
Hello @Mellvik,

> Do either of you have something up your sleeve?

Not really "up my sleeve"; more like "by the way":  I have been looking at the [Amsterdam Compiler Kit](https://github.com/davidgiven/ack), now maintained by David Given.  It currently already has a fully-working `i86` back-end _and_ a runtime library and support files for creating PC booter programs.  I am trying to add support to ACK for compiling `i86` programs for MS-DOS, with some success.

I did (also) look at [PCC](http://pcc.ludd.ltu.se/) a few weeks ago.  For some reason though, I could not get its `i86` compiler to build.  

Thank you!

**Comment by ghaerr** [comment]
Hello @Mellvik and @tkchia,

Interesting discussion a few years ago in #226 on compressing the kernel and/or using Exomizer-style compression for userland binaries. I think the trouble of implementing compression for the kernel or via the filesystem, especially if using a.out header bits, is probably not worth the effort, increased complexity and results at this point. But having self-decompressing executables could go a long way into more easily solving our 1.4MM floppy space issue. 

The big issue in my mind using Exomizer is: with the Exomizer decompressor contained in an ELKS a.out header binary, can it efficiently map/remap the code and data sections required, but not initially allocated by the kernel, when started? An efficient method would want to have the kernel pre-allocate the code and data segments prior to loading the Exomizer-containing binary, somehow.

Is ACK self hosted on `i86`? Was it once used to compile MINIX v1 on 8086, or was another compiler used? Its interesting thinking of hosting a C compiler on ELKS, although I don't see how much use it will get. Of course, `bcc` should be considered. As well as other languages: I've spent the last three months deep diving into various lisp and javascript engines, some of which I could quickly bring to ELKS, although I'm not sure what anyone would do with them!

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Is ACK self hosted on `i86`? Was it once used to compile MINIX v1 on 8086, or was another compiler used?

I have no idea actually.  I should probably try to grab an old Minix disk image and get some clues...

Thank you!

**Pull request merged**
