### PR TITLE
[kernel] New synchronization primitives

### PR DESCRIPTION
**Pull request by mfld-fr**
No impact except NE2K driver, tested through `telnetd` under QEMU.

### CODE REVIEW

**Comment by ghaerr** [comment]
Does this fix a bug, or is this a new feature? If only a new feature, is NE2K the only code that uses the previous/current wait primitives? Just asking for stability purposes for upcoming release.

Where is the old, replaced lock code? I don't see that being deleted.

A couple questions on include files:

1. What is the purpose of the include/arch/*.h files, versus include/linuxmt/*.h? That is, since atomic.h is now in linuxmt/, and defines entry points in architecture-specific atomic.S, shouldn't atomic.h be in linuxmt/?

2. I also realize that our include files are a bit messy at this point. Is the new standard to remove whole-file ifdef LX86_LINUXMT_WAIT_H for instance, and always use pragma once? I don't know whether that pragma is a standard or whether we're now marrying our .h files to a gcc-only compiler.

Nice to see unneeded lock.h includes removed from various kernel sources.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> I don't know whether that pragma is a standard or whether we're now marrying our .h files to a gcc-only compiler.

It is not standard, but apparently [quite widely supported](https://en.wikipedia.org/wiki/Pragma_once#Portability).  Personally I would still prefer the original include guards though.

Thank you!

**Comment by tkchia** [comment]
Regarding the locking logic itself, I am not familiar with the ins and outs of this particular type of Ethernet card, so I will have to defer to you all.

Thank you!

**Comment by mfld-fr** [comment]
Not a bug fix - rather a preparation step.

The current `sleep_on` is still unsafe (see #222) and it fails when used with NE2K as a fast device (ethernet...). Fixed by introducing a first version of `wait_event` some times ago, only for NE2K. Now introducing some more safe primitives, but had to rework `wait_event` for non-static conditions, so impacting again NE2K.

Other parts of the kernel are unchanged. Still use the unsafe `sleep_on`, the old semaphore, or even shared data **not** protected against concurrent access. New synchronization primitives will help to have a more robust code for reference counting and locking.

About the headers : `atomic.h` and `lock.h` are in `include/linuxmt` because interface of the primitives is not architecture dependent. Atomics implementation is specific to 8086 architecture, so `atomic.S` is under `arch/i86`.

**Comment by ghaerr** [comment]
> Regarding the locking logic itself, I am not familiar with the ins and outs of this particular type of Ethernet card, so I will have to defer to you all.

Neither am I, so I defer to @mfld-fr as well.

@mfld-fr, thank you for the explanation, and this contribution.

**Pull request merged**
