### PR TITLE
[kernel] Fix kernel sbrk system call

### PR DESCRIPTION
**Pull request by ghaerr**
This fixes a major bug in the ELKS kernel, which affected all programs that use `sbrk`, including programs calling `malloc`, `execvp`, and `execve`, and more.

`sbrk` is supposed to return the start address of allocated memory, instead it was returning the address just above the allocated memory. Thus, any program using `malloc` or `realloc` would end up with a pointer to bad memory on a request for more memory. It looks like this bug has been around for almost two years. I ended up finding it by actually using both `sash` and `sh` and noticed the system would crash after a few commands were run.

The C environment was being trashed by shell calls to `exec`, `sort` displayed corrupted data, and I'm sure this was the problem with the `realloc` call in `ls` earlier. All these problems are now fixed.

### CODE REVIEW

**Comment by jbruchon** [comment]
I knew there was something wrong related to this call a long time ago. Thanks for tracking it down. It could be responsible for tons of inexplicable issues. I'm committing it immediately. If anyone has problems, we can always revert later.

**Comment by ghaerr** [comment]
Thanks, it took a while to find it. I ended up using the `brk` debug message you put in the kernel long ago, which helped!

**Comment by jbruchon** [comment]
Now you know why it got put there! I was so frustrated with that. I was nowhere near as skilled in C back then as I am today, so I couldn't identify the problem after quite a bit of poking around and I gave up. I'm glad you said it was difficult. Now I know that I was justified in dropping my efforts (and I think something else was committed that made me think the issue was fixed.)

**Comment by mfld-fr** [comment]
Nice spot !

**Pull request merged**
