### PR TITLE
Pc98 bioshd2

### PR DESCRIPTION
**Pull request by tyama501**
Hello @ghaerr 

As I wrote in https://github.com/jbruchon/elks/issues/1325
this enhancement includes the following.

- Detect numbers of FD Drives.
- Probe 1440/1232 and support both

I installed the kernel to PC-9801BX hard disk and
booted from it and confirmed I could mnt/read/write both 1440/1232 disk.

Thank you!

### CODE REVIEW

**Comment by ghaerr** [comment]
Hello @tyama501,

Thanks for the continued enhancements. I'm glad you were able to figure out the kernel problem which resulted in the need for CONFIG_VAR_SECTOR_SIZE being always for PC-98, I hadn't thought of that.

I notice reading through bioshd.c that its starting to get complicated with the IBM vs PC-98 arch differences using ifdefs; at some point we'll probably want to implement function wrappers around a lot of that, to simplify understandability and maintenance. @cocus is asking for multiple partition support on his /dev/ssd flash block device driver and we'll probably need to pull those portions out of bioshd.c and into a shared file at some point also; I haven't really started looking at that.

That said, this is about the end of your wishlist which require changes in the BIOS block device driver, correct, or is there more?

Thank you!

**Comment by tyama501** [comment]
Hello @ghaerr ,

〉starting to get complicated with the IBM vs PC-98 arch differences using ifdefs;

I agree, I also think so.

〉this is about the end of your wishlist which require changes in the BIOS block device driver, correct, or is there more?

For  now, yes it is the end of the list.
I was asked to support 2DD 640KB which is the half of the 1232 on the twitter but I think it is beyond the scope of the 0.7.0.
Thank you.

**Comment by ghaerr** [comment]
> I was asked to support 2DD 640KB which is the half of the 1232 

FD1232 is CHS 77,2,8 with 1024 byte sectors, right? What is FD640, 77,2,8 w/512 byte sectors? That would be very easy to add, just another section in image/Make.defs, I think.

**Comment by tyama501** [comment]
Hello @ghaerr ,

>What is FD640, 77,2,8 w/512 byte sectors?

It seems 80,2,8 w/512 byte sector.
The device address is different (again) so there is some work to do.

**Pull request merged**
