### PR TITLE
Move to recent GCC-IA16

### PR DESCRIPTION
**Pull request by mfld-fr**
GCC-IA16 sourced from GitHub and built as per @tkchia advice (see tkchia/gcc-ia16#1).

### CODE REVIEW

**Comment by mfld-fr** [comment]
@jbruchon : GCC-IA16 build OK. I need to resynch on latest Juan's PR, so please merge this one (no impact on ELKS).

**Comment by lithoxs** [comment]
Should this be placed in the ELKS tree?. Even now, the BCC source tree is put besides the ELKS tree. Perhaps the conversion utility could be placed in arch/i86/tools. The binutils package is not used in any way now.
But the most important points are some questions I asked in issue #166. Looks like we are moving without any goal. Right now, all we have are some tricks to fake the build system to think it is still using BCC.

**Comment by jbruchon** [comment]
Am I correct that gcc doesn't build a working system yet?

**Comment by lithoxs** [comment]
No. The kernel built using any of ia16-unknown-elks-gcc or ia16-elf-gcc are able to boot, bring up the shell, run commands without crashing, etc. We need to make tests with diverse configurations and load levels to be sure it is fully working.
But I would say that this compilers do produce working systems.

**Comment by mfld-fr** [comment]
Today, for both BCC and GCC-IA16, user has to build manually the compiler, then link it to ELKS, and tune the Makefile globals. A first goal is build chain automation. I agree the built chain should be rather placed out of the tree, so I will move it later. But the automation scripts themselves have to be in the tree to have a common reference.

**Comment by mfld-fr** [comment]
The conversion utility is part of the build chain, not of ELKS, so it looks more logical to place it there.

**Comment by mfld-fr** [comment]
For the overall discussion about compiler, please continue the thread in jbruchon#166, not sparsely in many PR. Thanks.

**Comment by jbruchon** [comment]
Should I go ahead and merge this?

**Comment by mfld-fr** [comment]
Just sanity tested this recent GCC-IA16 version with default configuration and QEMU, no problem at a first glance. Please merge this one, it would set a common reference, even if everybody is free to use his own GCC-IA16 version. I will tune later this GCC-IA16 build & installation script after fixing more urgent regressions in non-default configuration.

**Pull request merged**
