### PR TITLE
[kernel] Add compile-time TZ= timezone string, FAT use localtime

### PR DESCRIPTION
**Pull request by ghaerr**
Allows for .config to contain TZ= timezone string to be compiled into kernel, eliminating requirement for editing /etc/profile or /bootopts to set local timezone, pursuant to discussion in https://github.com/jbruchon/elks/issues/1273#issuecomment-1115081566.

NOTE: `make menuconfig` will show new CONFIG_TIMEZONE TZ= option, but configure 'string' command is buggy and attempting to edit via `make menuconfig` will hang the configure, requiring a ^C exit. One must edit .config directly and add CONFIG_TIMEZONE="JST-9" etc directly. I have added this to pc98.config.

TZ=MDT6, TZ=JST-9 etc string will be automatically exported by /etc/profile into shell environment for proper libc time conversions. This is done in a bit tricky way by modifying /etc/profile with compiled-in TZ=CONFIG_TIMEZONE for during the build process.

/bootopts will override compiled-in TZ= string if set there.

FAT filesystem timestamps now saved in localtime.

@tyama501, I have tested this, but would definitely appreciate your taking a look at it to see how it works in Japan. I added the appropriate CONFIG_TIMEZONE to pc98.config which will need to be copied to your .config. The `clock -s -u` was not modified in /etc/rc.sys, the -u may need to be removed when a compiled-in timezone is set. We can talk about how we should automatically handle that in rc.sys should that be required. FAT files should now be saved in localtime.

### CODE REVIEW

**Comment by ghaerr** [comment]
Hello @jbruchon,

As I posted above, for some reason the 'string' command in the ELKS kernel configure mechanism seems to be completely broken. (That is, using `string 'Enter TZ string value' CONFIG_TIMEZONE ""` will crash menuconfig if entering a string is attempted, see elks/config.in in this PR). There are some other unused "string" commands elsewhere in ELKS but they're never executed or commented out of the config.in scripts, so this seems to be the first time we've tried to use it in years.

I was reading the make menuconfig documentation in elks/config and saw that you were the maintainer... that is back about 25 years ago!!! :) I was wondering if you had any idea how this could be fixed? I started looking at the Configure and Menuconfig scripts and it about blew my mind, and don't know where to start. Any help or tips would be appreciated.

Thank you!

**Comment by jbruchon** [comment]
I don't actually know that much about the inner workings of menuconfig. It was adopted from a very old Linux kernel and I always thought it'd be a good idea to completely redo that by stealing the much better developed menuconfig framework from a much newer Linux kernel. I wasn't the maintainer 25 years ago (I wasn't even in high school yet, IIRC) but I did "take over" the project in 2006 because I didn't want to watch it die. I think it was harkal [on SourceForge](https://sourceforge.net/projects/elks/) that responded to my request to get admin access by basically giving me full control of the project, and I've just sort of kicked it along ever since. It was a shambled-together mess from the start and menuconfig is the biggest legacy mess that has stuck around.

I'd say it's time to rip out the existing config system and pull a better one. I'd actually suggest using the config system used by [BusyBox.](https://www.busybox.net/) The Linux kernel's build system has added a lot of annoying dependencies while BusyBox remains fairly pure, plus BusyBox puts the config data at the top of the C files they manipulate rather than in some giant master config database. It would also be a great opportunity to NOT carry over all the useless and unused stuff such as unused config options.

**Comment by tyama501** [comment]
Hello @ghaerr ,

Thank you for this modification.

> I have tested this, but would definitely appreciate your taking a look at it to see how it works in Japan. 

I tested with PC-9801RX and now I can see the same time stamp for dos and elks with JST-9.

dos partition file from dos (05050115.txt, 22-05-05 1:16)
RTC_IMG_20220505_011638

dos partition file from elks (05050115.txt, May 5 01:16)
RTC_IMG_20220505_012003

elks disk file from elks (05050121.txt, May 5 01:22)
RTC_IMG_20220505_012320

elks disk file from dos (05050121.txt, 22-05-05, 1:22)
RTC_IMG_20220505_012647

I have noticed a issue for "date" command.
I will write about this in #1273.

**Comment by ghaerr** [comment]
Hello @tyama501,

Thank you for your testing! Glad that FAT file dates are now correct.

At some point, I am curious as to whether moving to compiled-in CONFIG_TIMEZONE="JST-9" support will work with clock command still running -u parameter (UTC) in /etc/rc.sys. Did you run the above tests with CONFIG_TIMEZONE="JST-9" compiled in? That should allow you to switch to your (preferred) RTC localtime, but not have to set TZ= every time you build an image.

What was not included in this PR is a way to exclude -u option from clock if TZ is set. Suggesting something like in /etc/rc.sys:
```
utc=
if test "$TZ" = ""; then utc=-u; fi
clock -s $utc
```

Thank you!

**Comment by tyama501** [comment]
Hello @ghaerr ,

Yes, I tested with CONFIG_TIMEZONE="JST-9" compiled in but I removed -u for clock -s in /etc/rc.sys by myself.

I think /etc/rc.sys should exclude -u automatically too.

Thank you!

**Comment by ghaerr** [comment]
> I think /etc/rc.sys should exclude -u automatically too.

Ok, I will add that to next PR.

Are you running with RTC set to localtime with these changes (instead of UTC?)

**Comment by tyama501** [comment]
Yes, I am always using RTC=local time.

Oh, this is not my case but how about the case RTC=UTC and the local time is not UTC?
(I don't think old PCs before world wide web using UTC but...)

In this case TZ will be set  but -u is needed...

**Comment by ghaerr** [comment]
> Oh, this is not my case but how about the case RTC=UTC and the local time is not UTC?
> In this case TZ will be set but -u is needed...

Very good point! Also QEMU scripts are typically being run with -rtc base=utc, which is just that case.
It sounds like additional thought is needed before making change removing clock -u (when CONFIG_TIMEZONE compiled in).

@Mellvik, are you using UTC or localtime on your real PCs? Any thoughts on this?

We could add yet another config option, CONFIG_RTC_IS_UTC, but that would have to translate to an environment variable to be checked in /etc/rc.sys. I don't want to commit to something without fully thinking this through or it could get messy.

**Comment by ghaerr** [comment]
Reading up [a little more](https://forums.linuxmint.com/viewtopic.php?t=265008) on this, it seems that Windows wants RTC in localtime, but Linux needs RTC in UTC. 

Thus, since ELKS is supposed to be Linux, it seems perhaps we should keep clock -u flag, keeping RTC in UTC, and make things work on ELKS using TZ= for localtime offset.

Comments?

**Comment by tyama501** [comment]
@ghaerr ,

Thank you for the information.
For PC-98, Linux is not major so I think most PC-98 has RTC with localtime.
Is it possible to have different rc.sys for CONFIG_ARC_PC98?

**Comment by ghaerr** [comment]
> For PC-98, Linux is not major so I think most PC-98 has RTC with localtime.
Is it possible to have different rc.sys for CONFIG_ARC_PC98?

Yes - but since clock.c is specially modified for CONFIG_ARCH_PC98, it could display message "PC-98: ignoring -u flag, assuming RTC is in localtime", and treat RTC as localtime without need for special modification to /etc/rc.sys.

What I don't understand yet is whether the testing that you are doing will work if RTC is set in UTC. It seems all your testing requires RTC in localtime, correct?

Doesn't running clock -u for you read the RTC in UTC (ignoring the TZ= string from /etc/profile)?

**Comment by tyama501** [comment]
I mean I am also using dos.
I think dos need localtime...

**Comment by ghaerr** [comment]
Hello @tyama501,

Since date command is working with mods, perhaps only thing that needs to be done is to (reversing my previous thought) add config option CONFIG_RTC_LOCALTIME. When this option set, /etc/rc.sys will (somehow) not use clock -u option. The PC-98 build would default to COFNIG_RTC_LOCALTIME, and /etc/rc.sys would just run clock -s.

This would allow all other users using RTC=UTC to operate without modification, unless they also wanted to set RTC in localtime.

Going this route also has the benefit that QEMU scripts can continue to operating using RTC set to UTC.

**Pull request merged**
