### PR TITLE
[fat] Add mkfat to create FAT volumes from ELKS

### PR DESCRIPTION
**Pull request by ghaerr**
Adds new `mkfat` utility to create FAT12, FAT16 or FAT32 filesystems from ELKS.
Can also be compiled up on Linux or macOS host systems and used to easily create test images.
Fixes all enhancements requested in #835.

Usage: mkfat [-fat32] device size-in-blocks

Works just like mkfs but creates FAT filesystem.
Automatically selects cluster size and FAT12/16/32 based on volume size, unless -fat32 switch used to force FAT32.
FAT32 volumes require a minimum of 32763 blocks (~32MB).

@toncho11, you're welcome to play around with this. I managed to fit it on the 360k disk image, so we can now go to town creating filesystems from all floppy images.

[fd360-fat.bin.zip](https://github.com/jbruchon/elks/files/5528097/fd360-fat.bin.zip)
[fd360-minix.bin.zip](https://github.com/jbruchon/elks/files/5528098/fd360-minix.bin.zip)

### CODE REVIEW

**Comment by toncho11** [comment]
Hi,

mkfat is not on the fd360-fat.bin.zip supplied above.

**Comment by toncho11** [comment]
It does not boot. 

Also if I set 8000 (8MB) blocks it insists to use fat32. It checks the partition size (which is around 276 MB) or the blocks supplied as a parameter ? I could not create a fat16 partition. And fat32 does not boot. It says "ELKS.3".

**Comment by toncho11** [comment]
It also says commit 8219f717 when booting from floppy.

**Comment by ghaerr** [comment]
Thanks @toncho11 for your testing, I really appreciate it!

> Also if I set 8000 (8MB) blocks it insists to use fat32. 

Fixed. I had a uninitialized variable. It should create FAT16 now properly.

> It checks the partition size (which is around 276 MB) or the blocks supplied as a parameter ? 

No, just the blocks parameter. The partition size is not checked.


> And fat32 does not boot. It says "ELKS.3".

Yes, aware of that. ELKS does not yet support booting from FAT32.

Here's the updated 360's:

[fd360-fat.bin.zip](https://github.com/jbruchon/elks/files/5531539/fd360-fat.bin.zip)
[fd360-minix.bin.zip](https://github.com/jbruchon/elks/files/5531540/fd360-minix.bin.zip)



Thank you!

**Comment by toncho11** [comment]
It works now on fat16.

No we have a full install process without the need of external tools!

Thanks for all your hard work! A lot of progress has been made!!!

**Comment by ghaerr** [comment]
Thank you too @toncho11 for your testing and requesting it in the first place! We wouldn't have done it without you!
I'm going to take a quick pass at getting FAT32 boot working.

**Pull request merged**
