### PR TITLE
[net] ftp server for ELKS, supporting basic file transfer functionality.

### PR DESCRIPTION
**Pull request by Mellvik**
`ftpd` implements basic `FTP` file transfer service for ELKS. The server has been rewritten from scratch because everything else found on the net was either too big and complicated or too simple and special purpose oriented.

This is a first cut, which has been tested on physical hardware and generally works. There's a lot of debugging stuff in the code, and a `-d` option has been added to activate ample debug output. The amount of debug output will be reduced later.

In this version, the program does not disconnect from the controlling terminal. Use `&` to background it if desired. This will be fixed later.

Other issues:
- Passive mode is not yet supported.
- Globbing is not support yet. `MGET <directory>` works, `MGET x*` does not.
- Commands supported: `get mget put mput dir user pass type cwd pwd bye` and some other commands not visible to the user.
- `mget` will currently not filter out directories from the list of files to get.
- Login  is supported (required) but nonfunctional in the sens it does not check anything. Access is entirely open.  

The codes has a number of FIXMEs, to be addressed later.

### CODE REVIEW

**Comment by ghaerr** [comment]
Wow, you have been busy! Nice work!

Let's see whether the hack suggested in https://github.com/jbruchon/elks/issues/996#issuecomment-965547081 to ktcp for reusing the local port works.

If so, I can add the SO_REUSEADDR option and you can push a fix to this, or would you rather this get committed now?

Can you add elkscmd/inet/ftp/Makefile and other changes so this builds with the make system?

**Comment by Mellvik** [comment]
> 
> Let's see whether the hack suggested in #996 (comment) to ktcp for reusing the local port works.
> 
First thing in the morning, thank for a very efficient an productive session.
> If so, I can add the SO_REUSEADDR option and you can push a fix to this, or would you rather this get committed now?
> 
> Can you add elkscmd/inet/ftp/Makefile and other changes so this builds with the make system?
> 
Will update the PR tomorrow, thank you.

M

**Comment by Mellvik** [comment]
Added Makefile, also added a minor fix to `ls`: When outputting to a non-tty, `ls` must deliver clean file names, not space padding. This fix removed the padding.

The socket address reuse problem is still pending.

**Comment by Mellvik** [comment]
Comment about the `ls` fix:
`ls` is frequently used in scripts (via pipes) and other contexts to provide lists of files, one per line. In such contexts it is always assumed that the file list is clean. i.e. no beginning or trailing spaces, no extraneous characters except newlines.

ELKS `ls` added extra blanks to file names in such contexts, thus making its output unusable in scripts (and in contexts such as `ftpd` where I decided to ditch it in favor of a much faster `opendir()/readdir()` ).

This minimal change fixes the problem.

**Comment by ghaerr** [comment]
@Mellvik, are you OK with me committing this now?

> ELKS ls added extra blanks to file names in such contexts, thus making its output unusable in scripts (and in contexts such as ftpd 

Got it, sounds good.

I would like to test some of the issues mentioned in #999, as well as commit #1000, to help solve the remaining out of memory problem(s).

**Pull request merged**
